### ISSUE TITLE
按照issue 3获取access token时出现error70011

### ISSUE THREAD

**Issue by polychromate** [spencerwooo/onedrive-cf-index#100]
在操作步骤5的时候出现了error提醒，按照issue13[https://github.com/spencerwooo/onedrive-cf-index/issues/13](url)的解决方法，insomnia提示报错error70011，如下图所示
![image](https://user-images.githubusercontent.com/22171674/107966360-b1bc4900-6fe6-11eb-873f-16dda6903467.png)

>{
  "error": "invalid_scope",
  "error_description": "AADSTS70011: The provided value for the input parameter 'scope' is not valid. The scope 'offline_access$20Files.Read Files.Read.All' does not exist.\r\nTrace ID: 405cf278-c93a-461b-a7cd-c1ebaba23f00\r\nCorrelation ID: f814c053-4336-4622-b75a-547b38b77d34\r\nTimestamp: 2021-02-15 12:09:58Z",
  "error_codes": [
    70011
  ],
  "timestamp": "2021-02-15 12:09:58Z",
  "trace_id": "405cf278-c93a-461b-a7cd-c1ebaba23f00",
  "correlation_id": "f814c053-4336-4622-b75a-547b38b77d34"
}

我的form参数设置为
> client_id = 应用程序(客户端) ID
> code = 步骤4得到的code
> scope =  offline_access$20Files.Read%20Files.Read.All
> redirect_uri = https://heymind.github.io/tools/microsoft-graph-api-auth
> grant_type = authorization_code
> client_secret = 客户端密码

head参数为
> Content-Type = application/x-www-form-urlencoded

post地址为
> https://login.microsoftonline.com/common/oauth2/v2.0/token 

万分感谢!

**Comment by spencerwooo** [comment]
额不会是因为你 scope 里面第一个 $ 应该是 % 吧

```diff
- scope: offline_access$20Files.Read%20Files.Read.All
+ scope: offline_access%20Files.Read%20Files.Read.All
```

![image](https://user-images.githubusercontent.com/32114380/107977622-5e51f700-6ff6-11eb-8470-ecae7ccbf759.png)

**Comment by polychromate** [comment]
非常感谢
