### ISSUE TITLE
office教育版无法获取token

### ISSUE THREAD

**Issue by polychromate** [spencerwooo/onedrive-cf-index#101]
在生成 OneDrive API 令牌的5.2步骤中，authorize之后登录office教育版账号，点击授权，然后跳转回https://heymind.github.io/tools/microsoft-graph-api-auth 页面时，无法获取code，同样的方法在使用office个人版的时候没有问题，能获取code

**Comment by Ci10010** [comment]
> 在生成 OneDrive API 令牌的5.2步骤中，authorize之后登录office教育版账号，点击授权，然后跳转回https://heymind.github.io/tools/microsoft-graph-api-auth 页面时，无法获取code，同样的方法在使用office个人版的时候没有问题，能获取code

我遇到过，你可以打开浏览器控制台看返回信息，是因为你的那个教育版账号没有权限，你需要成为你那个教育版账号的管理员。如果你账号是买来的，那几乎没可能，只能放弃这个账号。

**Comment by spencerwooo** [comment]
@polychromate 确实有这种可能，这个情况就不在我们能控制的范围之内了，建议使用国际版 OneDrive。
