### ISSUE TITLE
CLI tool to simplify the grant token flow

### ISSUE THREAD

**Issue by beetcb** [spencerwooo/onedrive-cf-index#102]
> 本来这个小工具是我在其它项目中写的，但是我觉得很方便，很希望能整合到此项目中，帮助 **那些在部署之路上挣扎的同学**

hi @spencerwooo 新年好，我写了个 CLI 工具用来验证获取 `token`，先列一下教程里那个在线网站的问题：
- 获取容易出错
- 不支持世纪互联

这个 CLI 工具(名为 [ms-graph-cli](https://github.com/beetcb/ms-graph-cli)) 试图用简单的交互式命令行来解决这些问题，部署可以直接输出 `refresh_token`，大致效果为：

<details>
<summary>Demo SVG</summary>
<p align="center">
    <img src="https://raw.githubusercontent.com/beetcb/ms-graph-cli/master/media/demo.svg" alt="demo" width="600">
</p>
</details>

使用方法：
```bash
# 直接输出结果
npx @beetcb/ms-graph-cli

# 把结果写入本地文件
npx @beetcb/ms-graph-cli --save
```

**Comment by beetcb** [comment]
svg 示例中 id 和 secret 都是瞎填的，所以显示 Bad request

**Comment by spencerwooo** [comment]
@beetcb 这种情况下的 `redirect_url` 有设置上的特殊要求吗？

**Comment by beetcb** [comment]
@spencerwooo 
没有：
在 OAuth2 规范中，授权成功重定向的 url 一定包含 code 参数。这个程序的逻辑是从 url param 上获取的 code，所以任何重定向地址都行

**Comment by beetcb** [comment]
区别就是重定向到有效网站会进去某个网站，重定向到 localhost 会无法加载

但是这两种情况都能地址栏都有 code 参数

**Comment by beetcb** [comment]
我的建议是 `redirect_uri` 设为 http://localhost 以免进入其他网站误导用户，毕竟这是个 CLI 工具
