### ISSUE TITLE
对 wrangler  部署不是很明白啊

### ISSUE THREAD

**Issue by cbdgftqs** [spencerwooo/onedrive-cf-index#103]
我fork了项目到自己的github下面，在linux上配置好wrangler ，那wrangler publish的时候是怎么把项目推到cf worker上的昵 ？也没看到wrangler 和github有什么关联啊？小白问题 大佬多指教。。

**Comment by spencerwooo** [comment]
GitHub 只是用来存储源代码的，wrangler publish 给 CloudFlare 的东西是项目编译出来的内容。

**Comment by cbdgftqs** [comment]
那wrangler 编译的项目在哪里昵   还是说要从GitHub上面拉到本地

**Comment by cbdgftqs** [comment]
> 
> 
> GitHub 只是用来存储源代码的，wrangler publish 给 CloudFlare 的东西是项目编译出来的内容。

那wrangler 编译的项目在哪里昵 还是说要从GitHub上面拉到本地

**Comment by spencerwooo** [comment]
是需要从 GitHub 上拉到本地然后用 wrangler 推到 CF
