### ISSUE TITLE
世纪互联版本应用授权获取Code时报错

### ISSUE THREAD

**Issue by Ci10010** [spencerwooo/onedrive-cf-index#107]
在Microsoft Azure中创建应用，按照你们文档一步一步来的，在【**4. Authorize for code**】步骤中授权报错，如图![](https://cdn.nlark.com/yuque/0/2021/png/1563060/1613800417711-cb0a4db4-12ef-4518-bb67-164eff8e0762.png)
,这一步点击“接受”会报错，报错信息如下：
——————————————————————————————
![](https://cdn.nlark.com/yuque/0/2021/png/1563060/1613837932048-2afe8081-f6f8-4192-b491-9c831b5eb7cd.png)
——————————————————————————————
相似问题：https://stackoverflow.com/questions/48679308/invalid-delegation-token-invalid-national-cloud-id-1-is-specified
好像需要构造一个请求，但我不知道该如何处理。。

**Comment by Ci10010** [comment]
报错信息是
---------------------
登录
抱歉，登录时遇到问题。

AADSTS900433: Invalid National Cloud Token.
---------------------

**Comment by beetcb** [comment]
@Ci10010 试一下更新后的说明文档中的获取工具

![Screenshot_20210222-112126](https://user-images.githubusercontent.com/63141491/108652902-37b52400-7500-11eb-85c2-4c4c570af4b1.jpg)

如需显示中文，请使用下面这条命令：
```sh
npx @beetcb/ms-graph-cli -l CN
```
