### ISSUE TITLE
Ran into error when trying to fetch an access token

### ISSUE THREAD

**Issue by alexzzx1999** [spencerwooo/onedrive-cf-index#11]
In the Microsoft Graph API tooling page, I was able to fetch a code in step 4, but cannot continue to get an access token, as it returned the following message:
```
"error":"invalid_request",
"error_description":"AADSTS90023: Cross-origin token redemption is permitted only for the 'Single-Page Application'
```
As shown, it requires a single-page application; however, the platform is intended to be 'web'.

**Comment by spencerwooo** [comment]
Dup #13
