### ISSUE TITLE
大佬，失败了

### ISSUE THREAD

**Issue by xwwbest** [spencerwooo/onedrive-cf-index#113]
export async function getAccessToken() {
|   const timestamp = () => {
|     return Math.floor(Date.now() / 1000)
 @ ./src/index.js 4:0-59 55:28-42 57:42-51
./src/config/default.js 24:19
Module parse failed: Identifier directly after number (24:19)
You may need an appropriate loader to handle this file type.
|    * to get following params: client_id, client_secret, refresh_token & redirect_uri.
|    */
>   refresh_token: ,
|   client_id: ',
|   client_secret: ,
 @ ./src/index.js 1:0-37 31:23-29 50:6-12 50:22-28 56:6-12 57:4-10 65:20-26 66:18-24 69:19-25 69:46-52 84:15-21 84:42-48 85:23-29 85:51-57 85:84-90 129:10-16 129:33-39 129:74-80 141:10-16 144:31-37
Error: webpack returned an error. You may be able to resolve this issue by running npm install.

**Comment by SakuraPuare** [comment]
需要更多信息
