### ISSUE TITLE
MKV格式文件不能在线观看

### ISSUE THREAD

**Issue by xwwbest** [spencerwooo/onedrive-cf-index#117]
如题！MKV格式文件不能在线观看！

**Comment by spencerwooo** [comment]
请提供一下复现链接？

**Comment by xwwbest** [comment]
解决了吗？还有就是要怎么更新！

**Comment by spencerwooo** [comment]
- 更新见：<https://github.com/spencerwooo/onedrive-cf-index/issues/115>
- MKV 视频能提供一个吗？以及确认能够使用 DPlayer 在线播放的。

**Comment by xwwbest** [comment]
我怎么私发你？毕竟直接发出来也不好

**Comment by spencerwooo** [comment]
稍等，你试一下在 `src/render/fileExtension.js` 里面加上一行 `mkv: preview.video,` 可能就能播放了？如果确实这样就解决了我就直接改了。

![image](https://user-images.githubusercontent.com/32114380/110114590-dd656e80-7def-11eb-8efc-8527cd7bcfd7.png)

**Comment by xwwbest** [comment]
搞定，可以看了

**Comment by xwwbest** [comment]
还有就是更新的问题，我没有把文件放到github仓库。而是直接放在本地端，请问这样要怎么更新比较方便呢？
