### ISSUE TITLE
配置指引的 redirect_uri 有问题

### ISSUE THREAD

**Issue by y67h41** [spencerwooo/onedrive-cf-index#118]
按照readme的指引配置之后，clouflare报错，在worker的console里报如是错误：

> Uncaught (in promise) getAccessToken error "{\"error\":\"invalid_client\",\"error_description\":\"AADSTS50011: The reply URL specified in the request does not match the reply URLs configured for the application: 'fb1babcf-29a1-4bee-966a-e861a0a4c12e'.\\r\\nTrace ID: 4035be1b-0f68-45f9-be44-5897bd292500\\r\\nCorrelation ID: 8ba75d05-e0a7-4867-8c82-d364a6b14dc5\\r\\nTimestamp: 2021-02-28 05:11:16Z\",\"error_codes\":[50011],\"timestamp\":\"2021-02-28 05:11:16Z\",\"trace_id\":\"4035be1b-0f68-45f9-be44-5897bd292500\",\"correlation_id\":\"8ba75d05-e0a7-4867-8c82-d364a6b14dc5\",\"error_uri\":\"https://login.microsoftonline.com/error?code=50011\"}"

查代码，发现redirect_uri在src/config/default.js里被设置为https://heymind.github.io/tools/microsoft-graph-api-auth，在巨硬处加上这个redirect_uri后就正常了🤣

所以说readme的指引配置里这一条还是有问题的：

> iv. Set Redirect URI (optional) to Web (the multiselect dropdown) and http://localhost (the URL).

在现在的程序运作方式和指引里取得refresh_token的方法下，得设置两个Redirect URI： http://localhost 和 https://heymind.github.io/tools/microsoft-graph-api-auth

**Comment by spencerwooo** [comment]
历史遗留问题了 （；´д｀）ゞ，主要是我自己是直接用本仓库进行部署的，我最初在巨硬那里设置的 `redirect_uri` 是 heymind.github.io 那个，但是新版有 CLI 工具之后使用 localhost 应该就是可以的了，总之保证巨硬和这里的 `config/default.js` 两处的 `redirect_uri` 一致就应该没有问题。

**Comment by y67h41** [comment]
啊这

我的意思是本仓库的 readme 和本仓库的 config/default.js 的 redirect_uri 不一样，可能会对按 readme 部署的不会排障的新用户造成困惑，可能得劳烦阁下改一下
