### ISSUE TITLE
部署失败

### ISSUE THREAD

**Issue by Qikaile** [spencerwooo/onedrive-cf-index#122]
大佬们有没有教程呀！这部署教程本地wrangler部署不行呀！感觉这好乱呀！wrangler login登录不行 wrangler config可以
添加环境变量:wrangler secret put REFRESH_TOKEN出现Error:  Your configuration file is missing the following field(s): ["account_id"]
疯了

**Comment by spencerwooo** [comment]
请仔细查看报错信息：

```
Error: Your configuration file is missing the following field(s): ["account_id"]
```

说明你的配置文件 `wrangler.toml` 中没有正确设置 `account_id` 这一变量。
