### ISSUE TITLE
[Bug] Private folder doesn't apply to secondary directories

### ISSUE THREAD

**Issue by tkfanswind** [spencerwooo/onedrive-cf-index#123]
现在只能第一级目录加？
二级 三级目录好像不生效。

例如
export const ENABLE_PATHS = ['Films/mo1', 'Films/mo2', 'NEW']

头两个二级目录不生效

**Comment by tkfanswind** [comment]
二级三级目录需要写全路径吗？怎么写？

**Comment by spencerwooo** [comment]
Bug 了，会修的会修的

**Comment by 0wQ** [comment]
> Bug 了，会修的会修的

这样大概应该可以解决 😂

https://github.com/spencerwooo/onedrive-cf-index/blob/9642518945cef9f197ed169aea11886afded890c/src/index.js#L21-L22
```
-    const publicPaths = DISABLE_PATHS.map(i => `/${encodeURIComponent(i).toLowerCase()}`)
-    const privatePaths = ENABLE_PATHS.map(i => `/${encodeURIComponent(i).toLowerCase()}`)
+    const publicPaths = DISABLE_PATHS.map(i => i.toLowerCase())
+    const privatePaths = ENABLE_PATHS.map(i => i.toLowerCase())
```

https://github.com/spencerwooo/onedrive-cf-index/blob/9642518945cef9f197ed169aea11886afded890c/src/auth/config.js#L18
```
-    export const ENABLE_PATHS = ['🌞 Private folder']
+    export const ENABLE_PATHS = ['/🌞 Private folder']
```

**Comment by spencerwooo** [comment]
没 encodeURIComponent 的话，文件夹名如果包含 Emoji 就不行了

**Comment by 0wQ** [comment]
> 没 encodeURIComponent 的话，文件夹名如果包含 Emoji 就不行了

https://github.com/spencerwooo/onedrive-cf-index/blob/9642518945cef9f197ed169aea11886afded890c/src/index.js#L20-L22
```
const pathname = decodeURIComponent(new URL(request.url).pathname).toLowerCase()
const publicPaths = DISABLE_PATHS.map(i => i.toLowerCase())
const privatePaths = ENABLE_PATHS.map(i => i.toLowerCase())
```
