### ISSUE TITLE
wrangler preview出现问题

### ISSUE THREAD

**Issue by Qikaile** [spencerwooo/onedrive-cf-index#124]
![11](https://user-images.githubusercontent.com/51025570/110053164-d27cf080-7d93-11eb-85a9-3729d0e05114.JPG)

**Comment by Qikaile** [comment]
REFRESH_TOKEN是怎么有些人可以wrangler secret put REFRESH_TOKEN直接导入！

**Comment by spencerwooo** [comment]
第一个问题是你没有设置 `AUTH_PASSWORD` 变量，具体请参考：[🔒 私有文件夹](https://github.com/spencerwooo/onedrive-cf-index/blob/master/README-CN.md#-%E7%A7%81%E6%9C%89%E6%96%87%E4%BB%B6%E5%A4%B9)。如果不需要 Private 目录功能可以将 `src/auth/config.js` 文件中的 `AUTH_PASSWORD` 注释掉：

```diff
- // export const PASS = AUTH_PASSWORD
+ export const PASS = ''
```

第二个问题可能是 `REFRESH_TOKEN` 大于 1KB，请参考：<https://github.com/spencerwooo/onedrive-cf-index/issues/58>
