### ISSUE TITLE
如何添加多个onedrive？

### ISSUE THREAD

**Issue by tkfanswind** [spencerwooo/onedrive-cf-index#125]
多个onedrive请问如何添加到一个页面？
用不同目录显示

**Comment by spencerwooo** [comment]
目前并不支持这一功能，以及为什么会有多个 OneDrive？白嫖来的吗？

**Comment by tkfanswind** [comment]
有多个域的onedrive大量备份

**Comment by spencerwooo** [comment]
我觉得其实，你可以在 CloudFlare 部署多个本项目，然后使用一个 landing page 来串联各个项目。总之呢，我觉得这个问题不在本项目的考虑范围内。

**Comment by tkfanswind** [comment]
好的。请问能给个推荐的 landing page模板吗?thanks

**Comment by spencerwooo** [comment]
呃这个我就不太清楚了

**Comment by tkfanswind** [comment]
github一个项目只能fork一次，部署多个本项目，咋实现的？分支吗？分支有些参数是唯一的，会重名，action也不好处理。大佬求助下
