### ISSUE TITLE
Ran into error while attempting to fetch an access token 

### ISSUE THREAD

**Issue by alicetsai2001** [spencerwooo/onedrive-cf-index#13]
In the Microsoft Graph API Auth tooling page, when proceeding step 5, I encountered the following message...
```
{"error":"invalid_request",
"error_description":"AADSTS90023: Cross-origin token redemption is permitted only for the 'Single-Page Application' client-type.
```
As shown, it wants a `Single-Page Application`; however, the platform we are after is `Web`...

**Comment by spencerwooo** [comment]
OK. So it's not just me who is running into this problem. I think the original [online token generation tool](https://heymind.github.io/tools/microsoft-graph-api-auth) is broken for "Step 3 - Refresh Token", i.e, fetching the refresh token. I was able to fetch the `code` using the online tool in Step 1 and Step 2, and make a `POST` request manually to `https://login.microsoftonline.com/common/oauth2/v2.0/token` using [Insomnia](https://insomnia.rest/) for the `refresh_token`.

The request should be structured as follows:

```http
POST https://login.microsoftonline.com/common/oauth2/v2.0/token
Content-Type: application/x-www-form-urlencoded

client_id={client_id}&redirect_uri={redirect_uri}&client_secret={client_secret}
&code={code}&grant_type=authorization_code
```

![image](https://user-images.githubusercontent.com/32114380/89728889-25433380-da63-11ea-8d78-df0b2f52697e.png)

This authorization process is documented at: [Authorization and sign-in for OneDrive in Microsoft Graph | Code flow](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/getting-started/graph-oauth?view=odsp-graph-online#code-flow). Can you try this method?

**Comment by alicetsai2001** [comment]
Also works in my case - many thanks!!!

**Comment by spencerwooo** [comment]
All right, I'll leave a note in `README.md` afterwards.

**Comment by beetcb** [comment]
Considering @spencerwooo had already demonstrated  **` Chinese 21Vianet OneDrive` 's manually POST method**， I changed my fork `README.md` to ( just ) a quick tutorial ( in Chinese ) . Respect 😎

**Comment by riglaze** [comment]
My apologies for reopening this issue, but it looks like the `redirect_uri` is invalid now. It shows an error `redirect_uri value must be a valid absolute URI` everytime I try to get the code. Any help is greatly appreciated :)

**Comment by spencerwooo** [comment]
> My apologies for reopening this issue, but it looks like the `redirect_uri` is invalid now. It shows an error `redirect_uri value must be a valid absolute URI` everytime I try to get the code. Any help is greatly appreciated :)

@riglaze Which step? Did you try using Postman / Insomnia to perform the second request manually?

**Comment by riglaze** [comment]
> @riglaze Which step? 

Step 5, the process in which the user gets the `refresh_token`. I used the [guide](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/getting-started/graph-oauth?view=odsp-graph-online#code-flow) you linked, but it gives me that error

> Did you try using Postman / Insomnia to perform the second request manually?

Not yet. Will give it a shot soon

**Comment by spencerwooo** [comment]
> Step 5, the process in which the user gets the `refresh_token`.

My apologies if I haven't made this clear. **The online tool is broken for step 5 and all furthur steps**, for the step to get the `refresh_token` you'll have to perform the actual request manually.

1. USE THE ONLINE TOOL on "4. Authorize for code" to get a valid `Code` for the next step.
2. USE YOUR OWN TOOL TO STRUCTURE A REQUEST instead of using the online tool's "5. Exchange Access Token".

After these two steps, you'll get what you need: your `access_token` and your `refresh_token`.

**Comment by riglaze** [comment]
> > Step 5, the process in which the user gets the `refresh_token`.
> 
> My apologies if I haven't made this totally clear. **The online tool is broken for step 5 and all further steps**, for the step to get the `refresh_token` you'll have to perform the actual request manually.
> 
> 1. **USE THE ONLINE TOOL** on "4. Authorize for code" to get a valid `Code` for the next step.
> 2. **USE YOUR OWN TOOL TO PERFORM A REQUEST** instead of using the online tool's "5. Exchange Access Token".
> 
> After these two steps, you'll get what you need: your `access_token` and your `refresh_token`.

Thanks for the help. It is clear now

**Comment by rokibhasansagar** [comment]
On __Step 5. Exchange Access Token__ from https://heymind.github.io/tools/microsoft-graph-api-auth, I got refresh_token of 1031 character.
__EDIT: I tried manual method using Postman__, still getting tokens of same length
 
Then on last step __Refresh Token__, I pasted that token and got back another token of 1038 character.

I guess the final one is the token which needs to be on the CF Worker.

But CF Worker does not accept secret/token larger than 1kB and I get error while putting secret through wrangler, `Your secret is too large, it must be 1kB or less`.

What should be done?

**Comment by spencerwooo** [comment]
@rokibhasansagar See #58 if you can read Chinese, basically it's just a matter of storing your over-length access token through Cloudflare KV storage instead of Cloudflare secrets.

**Comment by xiaoxin2007** [comment]
@spencerwooo Can you write it in Chinese? I also met this problem but I can't read it. I can't read English, please.

**Comment by polychromate** [comment]
![image](https://user-images.githubusercontent.com/22171674/107870029-e1c4f880-6ecf-11eb-8cfa-18cbd0db437f.png)
When i use insomnia, it always show me error70000, I don't know why.

**Comment by beetcb** [comment]
hi @polychromate , looks like `code` has expired, try to refresh it(the `authorization code`).

**Comment by polychromate** [comment]
![image](https://user-images.githubusercontent.com/22171674/107945084-12895880-6fca-11eb-80de-054728165679.png)
@beetcb I resend a new code, now it shows me error70011. 

> The provided value for the input parameter 'scope' is not valid. The scope 'offline_access$20Files.Read Files.Read.All' does not exist.

**Comment by beetcb** [comment]
Plz do read `error_description` carefuly, it complains a invalid `scope`: 

![image](https://user-images.githubusercontent.com/63141491/107945689-f639eb80-6fca-11eb-843e-8b730adf4b52.png)

**Comment by spencerwooo** [comment]
@polychromate Please open a new issue to discuss your problems. ❤️
