### ISSUE TITLE
建议直接把refresh_token彻底放在CF workers KV中

### ISSUE THREAD

**Issue by shzxm** [spencerwooo/onedrive-cf-index#131]
建议直接把refresh_token彻底放在CF workers KV中
目前大部分refresh_token都超过了1kb的限制,这样会导致github action部署变得不可以用
同时应该修改
src/auth/onedrive.js

**Comment by naicfeng** [comment]
可以分片存储

修改`/src/config/default.js`
```
refresh_token: REFRESH_TOKEN_1 + REFRESH_TOKEN_2,
```

然后分两个环境变量存储，目前最方便的解决方法

**Comment by shzxm** [comment]
> 可以分片存储
> 
> 修改`/src/config/default.js`
> 
> ```
> refresh_token: REFRESH_TOKEN_1 + REFRESH_TOKEN_2,
> ```
> 
> 然后分两个环境变量存储，目前最方便的解决方法

居然还能这么整,神奇了
