### ISSUE TITLE
Help Can you please make video tutorial how to install from 0?

### ISSUE THREAD

**Issue by YinnVI** [spencerwooo/onedrive-cf-index#144]
Help Can you please make video tutorial how to install from 0?

**Comment by reaitten** [comment]
the author has already provided step-by-step instructions with pictures in the [readme](https://github.com/spencerwooo/onedrive-cf-index#deployment), if you are capable to read, and able to follow instructions, then this will be fairly easy.
if you don't know how to do a specific thing, google is always your friend.

**Comment by YinnVI** [comment]
![image](https://user-images.githubusercontent.com/26527969/112761090-a582cd00-9023-11eb-8abe-c8801b986d54.png)

Error 1101

**Comment by reaitten** [comment]
you did not define "BUCKET" 
go to kv namespace, and create a namespace with the title "BUCKET"
![image](https://user-images.githubusercontent.com/52531973/112843718-e0f7b880-9070-11eb-846c-b81f5074bb2e.png)
and create keys with the following names with the corresponding values
![image](https://user-images.githubusercontent.com/52531973/112843859-0c7aa300-9071-11eb-95ee-3271de71e16d.png)

**Comment by spencerwooo** [comment]
Closing this as discussion moved to #146
