### ISSUE TITLE
Error 1101

### ISSUE THREAD

**Issue by YinnVI** [spencerwooo/onedrive-cf-index#146]
![image](https://user-images.githubusercontent.com/26527969/112832228-378be380-90bf-11eb-8188-309da143a28a.png)

**Comment by reaitten** [comment]
read my comment `[here](https://github.com/spencerwooo/onedrive-cf-index/issues/144#issuecomment-809376939)`.

**Comment by YinnVI** [comment]
> read my comment [here](https://github.com/spencerwooo/onedrive-cf-index/issues/144#issuecomment-809376939)

i try to redeploy but 
![image](https://user-images.githubusercontent.com/26527969/112847108-eedd2600-90d0-11eb-9f6c-0d03237ef116.png)

 Creating the secret for script name drive-od1
Error:  Code 10054: workers.api.error.text_binding_too_large
 Your secret is too large, it must be 1kB or less

**Comment by reaitten** [comment]
don't do that, do it manually via the website.
i forgot to add to my previous comment, you need to bind the kv namespace named "BUCKET" to the website in the settings.
![image](https://user-images.githubusercontent.com/52531973/112848009-a04e6e00-9075-11eb-9ca1-48c1ad8b498a.png)

**Comment by YinnVI** [comment]
> don't do that, do it manually via the website.
> i forgot to add to my previous comment, you need to bind the kv namespace named "BUCKET" to the website with the variable name "BUCKET" in the settings.
> doing it this way will bypass that error.
> also remove your image, it has your token.
> 
> ![image](https://user-images.githubusercontent.com/52531973/112848009-a04e6e00-9075-11eb-9ca1-48c1ad8b498a.png)

![image](https://user-images.githubusercontent.com/26527969/112848654-8131f980-90d2-11eb-828f-65d6b853f3d3.png)
Are REFRESH_TOKEN & CLIENT_SECRET added there? inside the BUCKET?

**Comment by YinnVI** [comment]
> don't do that, do it manually via the website.
> i forgot to add to my previous comment, you need to bind the kv namespace named "BUCKET" to the website with the variable name "BUCKET" in the settings.
> doing it this way will bypass that error.
> also remove your image, it has your token.
> 
> ![image](https://user-images.githubusercontent.com/52531973/112848009-a04e6e00-9075-11eb-9ca1-48c1ad8b498a.png)
> 
> this is also done via the "wrangler.toml" file
> ![image](https://user-images.githubusercontent.com/52531973/112848753-67fb5f80-9076-11eb-9665-b184356ff227.png)

![image](https://user-images.githubusercontent.com/26527969/112849567-6449f600-90d3-11eb-8903-2942abe84e0c.png)
Are REFRESH_TOKEN & CLIENT_SECRET added there? inside the BUCKET?

**Comment by reaitten** [comment]
> ![image](https://user-images.githubusercontent.com/26527969/112848654-8131f980-90d2-11eb-828f-65d6b853f3d3.png)
> Are REFRESH_TOKEN & CLIENT_SECRET added there? inside the BUCKET?

you need to add the name the keys as :
`client_secret` = your client secret
`onedrive` = your "access token", looks something like this in the beginning:`{"token_type":"Bearer","scope":"Files.Read Files.Read.All Files.ReadWrite.All profile openid email","expires_in":3599,"ext_expires_in":3599,"access_token":`
`refresh_token` = your refresh token
then add the values just like this: 
![image](https://user-images.githubusercontent.com/52531973/112849725-52d30080-9077-11eb-96e0-22b39dd61b57.png)

**Comment by YinnVI** [comment]
> refresh_token

![image](https://user-images.githubusercontent.com/26527969/112852744-6792b100-90d6-11eb-877b-0ad30e6a8aba.png)

![image](https://user-images.githubusercontent.com/26527969/112852980-a1fc4e00-90d6-11eb-8d33-7f13a5d56344.png)

---

![image](https://user-images.githubusercontent.com/26527969/112853184-cc4e0b80-90d6-11eb-846e-f60c5e085b46.png)

![image](https://user-images.githubusercontent.com/26527969/112853268-e0920880-90d6-11eb-8a11-736450bb2187.png)

---

![image](https://user-images.githubusercontent.com/26527969/112853346-f3a4d880-90d6-11eb-8af1-047f46294447.png)

Error i cant publish it

**Comment by reaitten** [comment]
you have to define "REFRESH_TOKEN" & "CLIENT_SECRET" in src/config/default.js (add token & secret to js file)

**Comment by YinnVI** [comment]
> you have to define "REFRESH_TOKEN" & "CLIENT_SECRET" in src/config/default.js (add token & secret to js file)

![image](https://user-images.githubusercontent.com/26527969/112855646-38317380-90d9-11eb-9edb-6ae15ff38458.png)
like this?

**Comment by reaitten** [comment]
correct

**Comment by reaitten** [comment]
> > you have to define "REFRESH_TOKEN" & "CLIENT_SECRET" in src/config/default.js (add token & secret to js file)
> 
> ![image](https://user-images.githubusercontent.com/26527969/112855748-4da69d80-90d9-11eb-9db7-0ba32d3dabaa.png)
> 
> like this?

correct

**Comment by YinnVI** [comment]
> > > you have to define "REFRESH_TOKEN" & "CLIENT_SECRET" in src/config/default.js (add token & secret to js file)
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/26527969/112855748-4da69d80-90d9-11eb-9db7-0ba32d3dabaa.png)
> > like this?
> 
> correct

![image](https://user-images.githubusercontent.com/26527969/112857029-a1fe4d00-90da-11eb-91a9-3be0e69d5994.png)

 @ ./src/index.js 1:0-37 41:23-29 60:6-12 60:22-28 66:6-12 67:4-10 75:20-26 76:18-24 79:19-25 79:46-52 94:15-21 94:42-48 96:23-29 96:51-57 96:84-90 140:10-16 140:33-39 140:74-80 152:10-16 155:31-37
Error: webpack returned an error. You may be able to resolve this issue by running npm install.

**Comment by reaitten** [comment]
add quotes to before and after the refresh_token, client_id, and client_secret like this ('SECRET')
![image](https://user-images.githubusercontent.com/52531973/112857529-f1af2b00-907e-11eb-883a-ffa9e5ffe9d1.png)

**Comment by YinnVI** [comment]
> add quotes to before and after the refresh_token, client_id, and client_secret like this ('SECRET')
> 
> ![image](https://user-images.githubusercontent.com/52531973/112857529-f1af2b00-907e-11eb-883a-ffa9e5ffe9d1.png)

Done, but 
![image](https://user-images.githubusercontent.com/26527969/112857956-98c1b000-90db-11eb-9523-e97401a54ed3.png)

`worker.js:1 Uncaught (in promise) ReferenceError: BUCKET is not defined
    at s (worker.js:1)
    at R (worker.js:1)
s @ worker.js:1
R @ worker.js:1
Uncaught (in response) ReferenceError: BUCKET is not defined
worker.js:1 Uncaught (in promise) ReferenceError: BUCKET is not defined
    at s (worker.js:1)
    at R (worker.js:1)
s @ worker.js:1
R @ worker.js:1
Promise.then (async)
(anonymous) @ worker.js:1
Uncaught (in response) ReferenceError: BUCKET is not defined
worker.js:1 Uncaught (in promise) ReferenceError: BUCKET is not defined
    at s (worker.js:1)
    at R (worker.js:1)
s @ worker.js:1
R @ worker.js:1
Promise.then (async)
(anonymous) @ worker.js:1
Uncaught (in response) ReferenceError: BUCKET is not defined`

https://drive-od1.asagichan.workers.dev/ still get 1101 error

**Comment by reaitten** [comment]
> > add quotes to before and after the refresh_token, client_id, and client_secret like this ('SECRET')
> > ![image](https://user-images.githubusercontent.com/52531973/112857529-f1af2b00-907e-11eb-883a-ffa9e5ffe9d1.png)
> 
> Done, but
> ![image](https://user-images.githubusercontent.com/26527969/112857956-98c1b000-90db-11eb-9523-e97401a54ed3.png)
> 
> `worker.js:1 Uncaught (in promise) ReferenceError: BUCKET is not defined at s (worker.js:1) at R (worker.js:1) s @ worker.js:1 R @ worker.js:1 Uncaught (in response) ReferenceError: BUCKET is not defined worker.js:1 Uncaught (in promise) ReferenceError: BUCKET is not defined at s (worker.js:1) at R (worker.js:1) s @ worker.js:1 R @ worker.js:1 Promise.then (async) (anonymous) @ worker.js:1 Uncaught (in response) ReferenceError: BUCKET is not defined worker.js:1 Uncaught (in promise) ReferenceError: BUCKET is not defined at s (worker.js:1) at R (worker.js:1) s @ worker.js:1 R @ worker.js:1 Promise.then (async) (anonymous) @ worker.js:1 Uncaught (in response) ReferenceError: BUCKET is not defined`
> 
> https://drive-od1.asagichan.workers.dev/ still get 1101 error

please show your "wrangler.toml"

**Comment by YinnVI** [comment]
> > > add quotes to before and after the refresh_token, client_id, and client_secret like this ('SECRET')
> > > ![image](https://user-images.githubusercontent.com/52531973/112857529-f1af2b00-907e-11eb-883a-ffa9e5ffe9d1.png)
> > 
> > 
> > Done, but
> > ![image](https://user-images.githubusercontent.com/26527969/112857956-98c1b000-90db-11eb-9523-e97401a54ed3.png)
> > `worker.js:1 Uncaught (in promise) ReferenceError: BUCKET is not defined at s (worker.js:1) at R (worker.js:1) s @ worker.js:1 R @ worker.js:1 Uncaught (in response) ReferenceError: BUCKET is not defined worker.js:1 Uncaught (in promise) ReferenceError: BUCKET is not defined at s (worker.js:1) at R (worker.js:1) s @ worker.js:1 R @ worker.js:1 Promise.then (async) (anonymous) @ worker.js:1 Uncaught (in response) ReferenceError: BUCKET is not defined worker.js:1 Uncaught (in promise) ReferenceError: BUCKET is not defined at s (worker.js:1) at R (worker.js:1) s @ worker.js:1 R @ worker.js:1 Promise.then (async) (anonymous) @ worker.js:1 Uncaught (in response) ReferenceError: BUCKET is not defined`
> > https://drive-od1.asagichan.workers.dev/ still get 1101 error
> 
> please show your "wrangler.toml"

![image](https://user-images.githubusercontent.com/26527969/112858431-0e2d8080-90dc-11eb-9b4e-be874f2e7749.png)

**Comment by YinnVI** [comment]
![image](https://user-images.githubusercontent.com/26527969/112858553-2c937c00-90dc-11eb-9db4-a2f4578b40e0.png)

**Comment by reaitten** [comment]
please rename kv namespace to "BUCKET" only, and remove "zone_id" from wrangler.toml

**Comment by YinnVI** [comment]
> rename kv namespace

rename it in the "wrangler.toml" only?

**Comment by reaitten** [comment]
> > rename kv namespace
> 
> rename it in the "wrangler.toml" only?

where "BUCKET-drive-od1", rename to "BUCKET"

**Comment by YinnVI** [comment]
> > > rename kv namespace
> > 
> > 
> > rename it in the "wrangler.toml" only?
> 
> where "BUCKET-drive-od1" is named, rename to "BUCKET"

i just rename "BUCKET" in the "wrangler.toml" only & re publish it
its work thank you so much

**Comment by reaitten** [comment]
> > > > rename kv namespace
> > > 
> > > 
> > > rename it in the "wrangler.toml" only?
> > 
> > 
> > where "BUCKET-drive-od1" is named, rename to "BUCKET"
> 
> i just rename "BUCKET" in the "wrangler.toml" only & re publish it
> its work thank you so much

you're welcome!!
