### ISSUE TITLE
Help How to set password to protect base path only, not the file

### ISSUE THREAD

**Issue by YinnVI** [spencerwooo/onedrive-cf-index#147]
How to set password to protect base path only, not the file?

**Comment by reaitten** [comment]
i presume you mean you want to have the folder password protected?
or do you want a password protected site where firstly visiting site, you need to enter username and password?

1. have a password protected folder inside the base folder. instructions [here.](https://github.com/spencerwooo/onedrive-cf-index#-private-folders)
2. not sure if possible but the author could maybe implement it.

**Comment by YinnVI** [comment]
> i presume you mean you want to have the folder password protected?
> or do you want a password protected site where firstly visiting site, you need to enter username and password?
> 
> 1. have a password protected folder inside the base folder. instructions [here.](https://github.com/spencerwooo/onedrive-cf-index#-private-folders) example: [https://storage.spencerwoo.com/🌞%20Private%20folder/](https://storage.spencerwoo.com/%F0%9F%8C%9E%20Private%20folder/)
> 2. not sure if possible but the author could maybe implement it.

When i edit "/🌞%20Private%20folder/" to base "/" & Publish
Error 1101, when i change it back to "/🌞%20Private%20folder/" its back running normal

**Comment by reaitten** [comment]
> > i presume you mean you want to have the folder password protected?
> > or do you want a password protected site where firstly visiting site, you need to enter username and password?
> > 
> > 1. have a password protected folder inside the base folder. instructions [here.](https://github.com/spencerwooo/onedrive-cf-index#-private-folders) example: [https://storage.spencerwoo.com/🌞%20Private%20folder/](https://storage.spencerwoo.com/%F0%9F%8C%9E%20Private%20folder/)
> > 2. not sure if possible but the author could maybe implement it.
> 
> When i edit "/🌞%20Private%20folder/" to base directory "/" & Publish it
> Error 1101, when i change it back to "/🌞%20Private%20folder/" its back running normal
> 
> My English badd... 😁

it's okay, can you show a screenshot on what the causes the error

**Comment by YinnVI** [comment]
> > > i presume you mean you want to have the folder password protected?
> > > or do you want a password protected site where firstly visiting site, you need to enter username and password?
> > > 
> > > 1. have a password protected folder inside the base folder. instructions [here.](https://github.com/spencerwooo/onedrive-cf-index#-private-folders) example: [https://storage.spencerwoo.com/🌞%20Private%20folder/](https://storage.spencerwoo.com/%F0%9F%8C%9E%20Private%20folder/)
> > > 2. not sure if possible but the author could maybe implement it.
> > 
> > 
> > When i edit "/🌞%20Private%20folder/" to base directory "/" & Publish it
> > Error 1101, when i change it back to "/🌞%20Private%20folder/" its back running normal
> > My English badd... 😁
> 
> it's okay, can you show a screenshot on what the causes the error

Just change `export const ENABLE_PATHS = ['/🌞 Private folder/Private folder']` to `export const ENABLE_PATHS = ['/']` in `src/auth/config.js` = ERROR 1101

Change BACK FROM `export const ENABLE_PATHS = ['/']` to  `export const ENABLE_PATHS = ['/🌞 Private folder/Private folder']` in `src/auth/config.js` = working normal

**Comment by spencerwooo** [comment]
Hacky way (implemented in PR #112) for matching the directory path of the URL, so providing only `/` unfortunately won't work.
