### ISSUE TITLE
在预览时可以正常使用,部署后出现问题

### ISSUE THREAD

**Issue by ladjeek-actions** [spencerwooo/onedrive-cf-index#150]
spencerwooo大佬,我部署你的OneDrive-cf-index时,用wrangler preview本地预览可以正常查看
![image](https://user-images.githubusercontent.com/77675898/113496661-78a44d80-952e-11eb-9382-dbfb604e05f7.png)
可当我用wrangler publish命令发布后Worker却出现了1101(500)错误
![image](https://user-images.githubusercontent.com/77675898/113496677-aa1d1900-952e-11eb-8e16-1d4a571d7984.png)
仓库地址: https://github.com/ladjeek-actions/onedrive-cf-index/
worker地址: https://drivepan.taiyu.workers.dev/

**Comment by spencerwooo** [comment]
抱歉信息太少，我也无从判断你的失败原因。
