### ISSUE TITLE
Cannot read property 'id' of null

### ISSUE THREAD

**Issue by jerrita** [spencerwooo/onedrive-cf-index#152]
操作方式应该与教程一致，预览和部署时出现了这个问题，导致500，能判断出是哪个地方操作错了吗？

![image](https://user-images.githubusercontent.com/28153001/115321669-e307ef80-a1b6-11eb-9e69-72d66be0c0ed.png)

**Comment by spencerwooo** [comment]
我觉得你可以尝试删掉 worker 重新部署，因为这个 `'id' of null` 感觉出现的比较 random，不知道是哪里（可能是 wrangler 部署的时候？）出现了问题导致 webpack 编译上传的 JS 有问题。

**Comment by mlsub** [comment]
我也遇到了一样的问题，删掉worker重新部署也一样，难道和版本有关？

**Comment by jerrita** [comment]
> 我也遇到了一样的问题，删掉worker重新部署也一样，难道和版本有关？

我换掉了SharePoint，现在可以了，可能是之前我没配置好的问题吧
