### ISSUE TITLE
那三个字体链接没法替换成国内的吗？ 好像瀑布流有点慢

### ISSUE THREAD

**Issue by huanx9** [spencerwooo/onedrive-cf-index#153]
RT

**Comment by spencerwooo** [comment]
是 `https://fonts.googleapis.cnpmjs.org`？这已经是阿里 cnpm 镜像的 Google Font 字体链接了。

**Comment by huanx9** [comment]
是的 然后 还有 `fonts.gstatic.cnpmjs.org` 感觉很拉胯..

**Comment by spencerwooo** [comment]
我不在国内没办法测试到底是原 Google Fonts 快还是 cnpm 的好，如果需要的话替换回原 Google Font 也是可以的。
