### ISSUE TITLE
移动端文件名过长不自动换行，撑破path

### ISSUE THREAD

**Issue by opoet** [spencerwooo/onedrive-cf-index#154]
如下图，文件名过长撑破path区域，导致显示异常

![image](https://user-images.githubusercontent.com/30021379/115996119-9a19c600-a610-11eb-88ad-68f91b429ff1.png)

在css的.patch内添加如下两条可以解决

```
.path {
    margin-bottom: 1.5rem;
    font-size: 0.88rem;
    color: #999;

    word-break: break-all;
    word-wrap: break-word;

}
```
</br>

文件名过长也会导致文件大小显示变乱

![image](https://user-images.githubusercontent.com/30021379/115996317-5e333080-a611-11eb-8527-1364fc6d8906.png)

**Comment by spencerwooo** [comment]
CSS 确实有问题，建议自己暂时改一下，后面有计划重构整个前端，当前版本暂时不做更新了。
