### ISSUE TITLE
[功能请求]希望可以添加全局cloudflare代理开关

### ISSUE THREAD

**Issue by Jason-2048** [spencerwooo/onedrive-cf-index#156]
如题，目前使用教育版office账号，直链存在学号和学校域名等个人信息，希望下载、预览等功能都通过cloudflare代理。
感谢不尽！

**Comment by spencerwooo** [comment]
直链存在学号和学校域名的问题我个人感觉貌似 Cloudflare 代理并不能解决 🤔，用 Cloudflare 代理的话那个链接也不会有变化的

**Comment by karuboniru** [comment]
> 直链存在学号和学校域名的问题我个人感觉貌似 Cloudflare 代理并不能解决 🤔，用 Cloudflare 代理的话那个链接也不会有变化的

代理之后下载者看到的路径不就成了 `domain.xxx/path/to/file?raw&proxied`，这种情况应该能做到隐藏真实 onedrive 路径的作用啊
