### ISSUE TITLE
@beetcb/ms-graph-cli 获取 refresh_token 失败

### ISSUE THREAD

**Issue by yanglwr** [spencerwooo/onedrive-cf-index#161]
![image](https://user-images.githubusercontent.com/32095100/117803226-f6275000-b288-11eb-9437-1d004cd28c8a.png)

到获取到 token 这一步直接提示 Get token failed!Bad Request

**Comment by spencerwooo** [comment]
> 然后请输入浏览器地址栏重定向的地址

指的不是 `http://localhost`，而是上一步骤中生成的 URL 访问并且认证之后浏览器地址栏中的 URL。

**Comment by yanglwr** [comment]
感

> > 然后请输入浏览器地址栏重定向的地址
> 
> 指的不是 `http://localhost`，而是上一步骤中生成的 URL 访问并且认证之后浏览器地址栏中的 URL。

感谢 👍
