### ISSUE TITLE
小白求救

### ISSUE THREAD

**Issue by wxydejoy** [spencerwooo/onedrive-cf-index#163]
![image](https://user-images.githubusercontent.com/81625961/118539759-63a01880-b782-11eb-86b8-8bc42565e1ac.png)
这玩意咋填
网上找不到教程
吐了

**Comment by spencerwooo** [comment]
目前上传功能还没移植的很完整，所以……暂时先手动把文件拽到相应的文件夹里面吧

**Comment by wxydejoy** [comment]
这个点秒回
大佬
那大佬知道这个东西怎么填吗
onemanager也没有教程
