### ISSUE TITLE
获取refresh_token时，Then enter the address you were redirected to(it's in your address bar): （这里填什么呢？）

### ISSUE THREAD

**Issue by leftchest** [spencerwooo/onedrive-cf-index#164]
非计算机专业零基础来挑战安装，请大大指导哦，感谢

**Comment by beetcb** [comment]
你只要填**在浏览器里**登录授权成功后浏览器跳转的那个页面的**地址栏链接**，差不多是下面这样：

```rs
// 很长的链接，并且还有时效性，可能几分钟之后就失效了，得重新来一遍
http://localhost/xxxxx?code=abc
```

@me22451688 

祝你挑战成功 😊

**Comment by me22451688** [comment]
已成功获取token，wrangler命令可以自动添加kv，关键wrangler secret put REFRESH_TOKEN和wrangler secret put CLIENT_SECRET这两个命令一直执行不成功，我猜想是命令添加worker里面的内容的把，命令操作不了，那手动修改worker内容可以吗？如果可以，请大大粘贴下worker内容的格式，我好粘贴后照样修改。目前看到了挑战成功的希望，感谢哦，哈哈

**Comment by spencerwooo** [comment]
> 我猜想是命令添加 worker 里面的内容的吧

是这样的，是将本项目编译成功部署到 Cloudflare Worker 的办法。

> 命令操作不了，那手动修改 worker 内容可以吗？

![image](https://user-images.githubusercontent.com/32114380/119262055-c73aa380-bbd1-11eb-9a13-6c46098b8bed.png)

我觉得可能不太行 o(￣┰￣*)ゞ

不如贴一下报错信息看一下两个命令为什么执行不通。

**Comment by leftchest** [comment]
另外，私人文件夹需要两层进入，怎么修改第一点击私人文件夹就需要输入密码呢

**Comment by beetcb** [comment]
> 哈哈哈，竟然神奇地成功了

我也失败过，大多时候是网络原因，其实直接在 Workers -> Environment Variables 就可以直接修改啦！Bucket 也可在此手动操作哈

> 除了普通版和世纪互联，教育版账号可以用吗?

没有完整测试过

你可以翻翻以前的 Issue 看看，或者直接走一遍 [获取refresh_token] 流程，一般这一步能成功就没问题
