### ISSUE TITLE
【功能请求】加入mkv等视频文件播放支持

### ISSUE THREAD

**Issue by SakuraPuare** [spencerwooo/onedrive-cf-index#169]
如题，希望能加入mkv等视频文件的在线播放支持

**Comment by 0wQ** [comment]
https://github.com/spencerwooo/onedrive-cf-index/blob/038de6171adec31f3f9624b45777c60b41ff9404/src/render/fileExtension.js#L44
mkv 好像已经支持了

**Comment by SakuraPuare** [comment]
> https://github.com/spencerwooo/onedrive-cf-index/blob/038de6171adec31f3f9624b45777c60b41ff9404/src/render/fileExtension.js#L44
> 
> 
> mkv 好像已经支持了
