### ISSUE TITLE
password?

### ISSUE THREAD

**Issue by Micraow** [spencerwooo/onedrive-cf-index#17]
This is really a good product, but I want to use it not only for public sharing of files, but also for my own use. So I want to know that it is impossible to implement an encryption function to encrypt the user name and user password of the specified folder, so that I can mount my entire directory to this display program.

**Comment by spencerwooo** [comment]
Password and authentication can be enabled here if this is what you mean [./src/auth/config.js](https://github.com/spencerwooo/onedrive-cf-index/blob/master/src/auth/config.js#L9-L11):

```javascript
const AUTH_ENABLED = true
const NAME = "admin"
const PASS = "password"
```

This feature is inherited from upstream so I'm not sure if this is actually what you are asking for.

**Comment by Micraow** [comment]
Yes, thank you. This is the feature I asked for.
When you finish testing it, please tell me.😀

**Comment by spencerwooo** [comment]
> Yes, thank you. This is the feature I asked for.
> When you finish testing it, please tell me.😀

You can just turn this on if you want...This is implemented by the original author.
