### ISSUE TITLE
有些视频无法预览

### ISSUE THREAD

**Issue by tkfanswind** [spencerwooo/onedrive-cf-index#170]
请问如何添加.avi扩展名的视频文件，使得默认是预览模式

**Comment by leftchest** [comment]
.wmv无法在线观看，只能下载吗？

**Comment by 0wQ** [comment]
https://github.com/spencerwooo/onedrive-cf-index/blob/1f5f90ce77c6335e2465919001142254d733246f/src/render/fileExtension.js#L40-L44

格式可以在这里添加，不过浏览器大概率不支持 `.avi` `.wmv`   **[Dplayer 测试](https://od-api.vercel.app/?path=%2FVideos%2FDemo%2F)**

**Comment by spencerwooo** [comment]
这里的视频能不能在线预览播放完全取决于 DPlayer 支不支持，与本项目没有太大关系。
