### ISSUE TITLE
Error 1101 无法正常使用

### ISSUE THREAD

**Issue by Tokisaki-Galaxy** [spencerwooo/onedrive-cf-index#171]
以前搭的玩意最近天天出Error 1101,最近又新搞了一个,网址是https://drive.tokisaki.workers.dev/确定按照教程的每一步去做且没有出错.但是结果还是一样的提示Error 1101错误.

另外cf控制台调试信息如下

Uncaught (in promise) getAccessToken error "{\"error\":\"invalid_grant\",\"error_description\":\"AADSTS9002313: Invalid request. Request is malformed or invalid.\\r\\nTrace ID: bbbbea4e-ef1f-4544-b84d-1dc561dc0c00\\r\\nCorrelation ID: 22f49672-6fc8-45b8-8ad3-75209717ecb9\\r\\nTimestamp: 2021-06-05 08:01:34Z\",\"error_codes\":[9002313],\"timestamp\":\"2021-06-05 08:01:34Z\",\"trace_id\":\"bbbbea4e-ef1f-4544-b84d-1dc561dc0c00\",\"correlation_id\":\"22f49672-6fc8-45b8-8ad3-75209717ecb9\",\"error_uri\":\"https://login.microsoftonline.com/error?code=9002313\"}"
Uncaught (in response) Error: internal error

**Comment by fyfh** [comment]
windows 10, debian 10最新的nodejs测试可行

**Comment by spencerwooo** [comment]
很多情况下都是你自己的 OneDrive API 各种各样的问题，看你的报错信息：

```json
{
  "error": "invalid_grant",
  "error_description": "AADSTS9002313: Invalid request. Request is malformed or invalid."
}
```

所以应该是你的 OneDrive token 的问题，跟你有没有跟着教程、你用什么系统部署……都没有什么关系。建议重新使用工具 [@beetcb/ms-graph-cli](https://www.npmjs.com/package/@beetcb/ms-graph-cli) 获取 token 重新部署。
