### ISSUE TITLE
wrangler login 执行时卡在 Waiting for API token...

### ISSUE THREAD

**Issue by ArSrNa** [spencerwooo/onedrive-cf-index#174]
已经完成前面任何一步的操作，也弹出了浏览器登录成功

但是命令行仍然提示⠦   Waiting for API token...
使用软件：Windows Terminal（Powershell）；Edge 91.0.864.41 (官方内部版本) (64 位)

**Comment by ArSrNa** [comment]
补充：在执行wrangler whoami 之后提示：Error: config path does not exist C:\Users\xxxx\.wrangler\config\default.toml. Try running `wrangler login` or `wrangler config`

**Comment by spencerwooo** [comment]
这是你自己的网络问题，wrangler 登录连接需要访问 Cloudflare 服务器，即使你成功打开登录了对面也未必给你发回来了正确的 token 给 wrangler。问题跟本项目无关。
