### ISSUE TITLE
Custom domain does not works

### ISSUE THREAD

**Issue by myl7** [spencerwooo/onedrive-cf-index#180]
Version: 1f5f90ce77c6335e2465919001142254d733246f
OneDrive Type: Global Developer E5

I completely followed the readme to deploy my onedrive-cf-index, and under workers.dev domain it works perfectly. But after following the suggested guide to setup custom domain, the custom domain gives 1101 meaning worker throwed an error.

Tests in worker edtor are all fine, even for GET the custom domain. The only broken one is accessing onedrive-cf-index via the custom doamin. Replacing the worker with a hello world one makes it work fine. I also tried to try catch the error and print it, which gives JSON parsing error at position 0 'e'.

**Comment by as535364** [comment]
I have the same issue with it
I test as the following issue from other similar project
https://github.com/pixiv-cat/pixivcat-cloudflare-workers/issues/4
I have no idea about this project may be blocked by OneDrive?
