### ISSUE TITLE
Failed to build and publish the project with wrangler

### ISSUE THREAD

**Issue by Micraow** [spencerwooo/onedrive-cf-index#19]
在我登陆之后，我尝试使用发布的命令。

```
wrangler publish
```

然后就遇到了这样子的问题。

```
 ./src/folderView.js 68:51
```

```
Module parse failed: Unexpected token (68:51)
You may need an appropriate loader to handle this file type.
|           'div',
|           ['style="min-width: 600px"'],
>           (!isIndex ? item('far fa-folder', '..', `${path}..`) : '') +
|             items
|               .map(i => {
 @ ./src/index.js 7:0-47 123:32-48
Error: webpack returned an error. You may be able to resolve this issue by running npm install.
```

**Comment by Micraow** [comment]
我也尝试了 npm install ,但是问题依然存在。

**Comment by spencerwooo** [comment]
npm 不知道行不行，你可以用 yarn 试一下吗

**Comment by spencerwooo** [comment]
先将当前文件夹下的 `./node_modules` 全部删除，然后用 `yarn` 重新安装依赖

**Comment by Micraow** [comment]
@spencerwooo 
我一开始就是用的是yarn,刚刚又按你所说的做里边，但是还是有相同的问题。今天是我的完整的过程。

PS C:\WINDOWS\system32> cd C:\Users\77933\Documents\od
PS C:\Users\77933\Documents\od> wrangler publish
added 183 packages from 107 contributors and audited 183 packages in 4.838s

25 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

 ./src/folderView.js 68:51
Module parse failed: Unexpected token (68:51)
You may need an appropriate loader to handle this file type.
|           'div',
|           ['style="min-width: 600px"'],
>           (!isIndex ? item('far fa-folder', '..', `${path}..`) : '') +
|             items
|               .map(i => {
 @ ./src/index.js 7:0-47 123:32-48
Error: webpack returned an error. You may be able to resolve this issue by running npm install.
PS C:\Users\77933\Documents\od>

**Comment by Micraow** [comment]
@spencerwooo 
问题仍然存在。我这边所有的程序都使用的是最新版的呀。

**Comment by spencerwooo** [comment]
找到问题了，我去看了你的 fork，你 51 行删多了：

![image](https://user-images.githubusercontent.com/32114380/91400729-bd6a5680-e872-11ea-96ef-8160920d1e76.png)

这里的 `intro` 改成：

```javascript
const intro = `<div class="intro markdown-body" style="text-align: left; margin-top: 2rem;">
                  <h2>Yoo, I'm Micraow Peng 👋</h2>
                  <p>This is MS's OneDrive SECRET directory . Please leave.</p>
               </div>`
```

这样修改之后我这边你的 fork 是可以 build 的了。

![image](https://user-images.githubusercontent.com/32114380/91400930-1cc86680-e873-11ea-88cc-3a577ae1d66f.png)

**Comment by Micraow** [comment]
好的，谢谢！

**Comment by Micraow** [comment]
额，还有一个问题啊，这是我应该在哪里更改页面上的标题？还有窗口的标题呢？
![IMG_20200827_145850](https://user-images.githubusercontent.com/48644801/91408095-d9bbc280-e875-11ea-8552-1b5260a7bc7a.jpg)

**Comment by spencerwooo** [comment]
@Micraow [./src/render/htmlWrapper.js](https://github.com/spencerwooo/onedrive-cf-index/blob/master/src/render/htmlWrapper.js)

**Comment by Micraow** [comment]
另外，我想知道缓存这一功能是否测试过了？以及我是否可以修改多大的文件可以预览，超过这一大小的文件是下载?

**Comment by spencerwooo** [comment]
> 另外，我想知道缓存这一功能是否测试过了？

缓存是原作者实现的，我没使用过，你可以自己试试。

> 以及我是否可以修改多大的文件可以预览，超过这一大小的文件是下载?

暂时没有类似的考虑，你可以选择自己实现。

**Comment by Micraow** [comment]
那，，请问你下一步准备做什么?
也许预加载要预览的文件不错。
