### ISSUE TITLE
叨扰大佬一下 我捣鼓了一晚上 一直获取不了refresh_token 

### ISSUE THREAD

**Issue by GrapeFruitWolfs** [spencerwooo/onedrive-cf-index#190]
恳请大佬帮助 这是以下代码

> D:\Microsoft_Graph_Security_API\QuickStarts\Node\onedrive-cf-index-main>npx @beetcb/ms-graph-cli
npx: installed 36 in 7.777s
? Please select your OneDrive or SharePoint account type: Global
? Please select your deploy type (OneDrive or SharePoint): OneDrive
? Enter your client_id: 1b973335-5c01-4a1f-9002-e4125725854b
? Enter your client_secret: -aHB.9kclrsDK-_p1~252c3prxu1Xxom~I
? Enter your redirect_uri ([Default] http://localhost):
? Use your browser to visit this URL for login and authorization:
https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=1b973335-5c01-4a1f-9002-e4125725854b&scope=File
s.Read.All+Files.ReadWrite.All+offline_access&response_type=code&redirect_uri=http://localhost
Then enter the address you were redirected to(it's in your address bar):
 https://a.a
Get token failed!Bad Request
{
  client_id: '1b973335-5c01-4a1f-9002-e4125725854b',
  client_secret: '-aHB.9kclrsDK-_p1~252c3prxu1Xxom~I',
  redirect_uri: 'http://localhost',
  auth_endpoint: 'https://login.microsoftonline.com/common/oauth2/v2.0',
  drive_api: 'https://graph.microsoft.com/v1.0/me/drive',
  graph_api: 'https://graph.microsoft.com/v1.0'
}

> D:\Microsoft_Graph_Security_API\QuickStarts\Node\onedrive-cf-index-main>wrangler publish
 Built successfully, built project size is 29 KiB.
Error: Something went wrong! Status: 400 Bad Request, Details {
  "result": null,
  "success": false,
  "errors": [
    {
      "code": 10021,
      "message": "Uncaught ReferenceError: REFRESH_TOKEN is not defined\n  at line 1\n  at line 1 in e\n  at line 1\n  at line 1\n"
    }
  ],
  "messages": []
}

**Comment by spencerwooo** [comment]
```
Then enter the address you were redirected to(it's in your address bar):
https://a.a
```

你这里是怎么理解的？在工具给你自动生成 URL 访问授权之后，浏览器地址栏会出现一个新的 URL，你应该输入这个 URL，而不是动图里面的示例性链接 `https://a.a`。
