### ISSUE TITLE
找不到 zone_id

### ISSUE THREAD

**Issue by People-11** [spencerwooo/onedrive-cf-index#192]
我没有自己的域名，CloudFlare中也没有任何的网站，我只想将它部署到Worker中然后通过xx.xx.workers.dev访问，但是找不到教程中所需的 zone_id 从而无法部署，并且我也无法在CloudFlare中添加 DRAFT worker，请问我应该如何操作？

**Comment by Huiaei** [comment]
不清楚没有域名是不是可行，我的域名是[freenom](www.freenom.com)免费注册的，有一年期限，然后按照cloudflare的引导，改到cloudflare管理了。

**Comment by beetcb** [comment]
@People-11  可以忽略，
具体看看 wrangler 文档，不行手动编辑 worker

**Comment by People-11** [comment]
> @People-11
> 可以忽略 zone-id，具体看看 wrangler 文档，不行手动编辑 worker

请问使用您的工具获取的token是否有有效期？如果有的话，请问此项目是否会自动刷新token？

**Comment by beetcb** [comment]
有，每次我们使用 refresh token 时，微软那边都会返回一个可能是新的 refresh token，咱们需要保存它；目前此项目是保存了的，但是没用上

#186 应该能解决这个问题，但没测试过
