### ISSUE TITLE
Publish时出现以下错误

### ISSUE THREAD

**Issue by People-11** [spencerwooo/onedrive-cf-index#193]
看大佬说其实不需要zone_id，所以就直接将wrangler.toml里的zone_id删除了，通过GitHub部署时出现如图错误
![Snipaste_2021-07-15_21-35-40](https://user-images.githubusercontent.com/41558215/125799549-4e12f7e3-c3db-4330-a8db-7ad0be0ec2d9.jpg)

**Comment by beetcb** [comment]
这是你填的吗?
如果是，它应该被 ''/“” 包裹，为字符串
如果不是， wrangler 编译时候给补上的（不太可能，它自动补上的应该是个字符串）
@People-11

**Comment by People-11** [comment]
> 这是你填的吗?
> 如果是，它应该被引号包裹，为字符串
> 如果不是， wrangler 编译时候给补上的（不太可能，它自动补上的应该是个字符串）
> @People-11

不是我填的

**Comment by beetcb** [comment]
不需要，REFRESH_TOKEN 和 "0.xxx" 二选一即可

**Comment by People-11** [comment]
> 不需要，REFRESH_TOKEN 和 "0.xxx" 二选一即可

问题已解决，非常感谢
