### ISSUE TITLE
File extension parsing is case-sensitive

### ISSUE THREAD

**Issue by Micraow** [spencerwooo/onedrive-cf-index#21]
文件预览对文件后缀的大小写敏感!
我的目录下有四个文件。
1.jpg
1.JPG
1.png
1.PNG

我发现只有
1.jpg
1.png 
这两项可以预览出来，另外两个后缀是大写的文件就无法预览，虽然他们的图标显示的和小写后缀的文件的图标是一样的，但是我却无法预览他们，只会直接下载。
我一开始以为这个是一个还没有做出来的新功能，接着我发现这其实是一个bug。

**Comment by LufsX** [comment]
改下就行了~

![image](https://user-images.githubusercontent.com/33221883/91448194-28844f00-e8ac-11ea-9510-529b9072c67e.png)

不过这样的话, `.PnG`、`.pNG`、`.PNg` 还是不兼容（我想没人这样写吧
