### ISSUE TITLE
无法获得 `refresh_token`

### ISSUE THREAD

**Issue by PaddyLin-xum** [spencerwooo/onedrive-cf-index#25]
{"error":"invalid_grant","error_description":"AADSTS70000: The provided value for the 'code' parameter is not valid. The code has expired.\r\nTrace ID: 7da0f588-0389-4720-a1a4-7858b95b5000\r\nCorrelation ID: 397ffa74-99eb-4e86-ba8e-cf91ab3783a5\r\nTimestamp: 2020-09-02 09:11:20Z","error_codes":[70000],"timestamp":"2020-09-02 09:11:20Z","trace_id":"7da0f588-0389-4720-a1a4-7858b95b5000","correlation_id":"397ffa74-99eb-4e86-ba8e-cf91ab3783a5","error_uri":"https://login.microsoftonline.com/error?code=70000

**Comment by spencerwooo** [comment]
```
The provided value for the 'code' parameter is not valid. The code has expired.
```

请仔细看 API 返回的报错信息。

**Comment by PaddyLin-xum** [comment]
还是无法解决，换个号也没用

**Comment by spencerwooo** [comment]
@PaddyLin-xum 这里出现的问题是你使用 [Microsoft Graph API Auth](https://heymind.github.io/tools/microsoft-graph-api-auth) 这个工具在 `4. Authorize for code` 步骤中获取到 `code` 后，没有及时进行下一步请求导致 `code` 过期，和更换账号没有任何关系。

**Comment by PaddyLin-xum** [comment]
可是我立马下一步了呀，这里指的及时是什么，求指教

**Comment by spencerwooo** [comment]
我不知道你怎么操作导致 `code` 过期的，你试过我在这里提到的这个办法吗：[issue #13](https://github.com/spencerwooo/onedrive-cf-index/issues/13#issuecomment-671027672)？
