### ISSUE TITLE
数据库密钥目前已弃用

### ISSUE THREAD

**Issue by PaddyLin-xum** [spencerwooo/onedrive-cf-index#26]
数据库密钥目前已弃用，可使用旧版 Firebase 令牌生成器。请使用 Firebase Admin SDK 来更新您的源代码。

**Comment by spencerwooo** [comment]
This is not a question.

**Comment by spencerwooo** [comment]
如何你想问为什么使用数据库密钥而不使用 Firebase Admin SDK，是因为我不想再安装一个庞大的依赖，而其唯一功能只是来让我访问一个可以直接用 Rest API 访问的值。
