### ISSUE TITLE
请问GitHub Actions 该如何配置？

### ISSUE THREAD

**Issue by wekingchen** [spencerwooo/onedrive-cf-index#27]
看了main.yml，不知道 CF_API_TOKEN 的格式是什么样的？请问需要填哪些信息？REFRESH_TOKEN、CLIENT_SECRET、FIREBASE_TOKEN 这三项值不需要填吗？

**Comment by spencerwooo** [comment]
- `CF_API_TOKEN` 是你本地 wrangler 登录和发布到 Cloudflare 的那个 API Token，见 [Obtaining your API token or Global API key](https://developers.cloudflare.com/workers/learning/getting-started#6b-obtaining-your-api-token-or-global-api-key).
- 不需要填写 `REFRESH_TOKEN`、`CLIENT_SECRET`、`FIREBASE_TOKEN`，因为这些 secret 跟通过 GitHub Actions 自动化构建发布此 Worker 无关，这些参数已经存在于 Cloudflare Worker 里面了，不需要每次发布都进行更新。
