### ISSUE TITLE
wrangler设置REFRESH_TOKEN失败，“Error: ⚠️  Code 10054: workers.api.error.text_binding_too_large”

### ISSUE THREAD

**Issue by xmxs** [spencerwooo/onedrive-cf-index#28]
错误详情是“Error: ⚠️  Code 10054: workers.api.error.text_binding_too_large
🕵️  Your secret is too large, it must be 1kB or less”

看了下从ms获取的refresh_token的确超过1k了，长度是1056。
请问这个有什么解决办法吗？

**Comment by xmxs** [comment]
![refresh_token too large](https://user-images.githubusercontent.com/5410657/92068201-d7f38100-edd8-11ea-9d4d-34f4c523fd0b.png)
错误详情如图。另外尝试了多次获取refresh_token均长度为1156。

**Comment by spencerwooo** [comment]
Dup #16

#16 里面讲了用 Firebase 而不用 Cloudflare Worker 环境变量存储 REFRESH_TOKEN 的方法，请参考这一方法存储你的 REFRESH_TOKEN。
