### ISSUE TITLE
有打算支持部署到Linux环境的想法吗

### ISSUE THREAD

**Issue by lizkes** [spencerwooo/onedrive-cf-index#29]
很喜欢这个project的外观，但是目前只支持部署到cloudflare上，国内用户访问速度不太理想。如果可以部署到linux上，那么就能解决这个问题。
有打算支持部署到Linux环境的想法吗

**Comment by spencerwooo** [comment]
显然类似方案中部署到 Linux 服务器上比部署到 Serverless 云环境要多得多，因此本项目我不准备支持部署到 Linux 服务器。另外 OneDrive 都不嫌慢的话 Cloudflare 更不是问题了吧？
