### ISSUE TITLE
预览图片时高度不正常

### ISSUE THREAD

**Issue by lizkes** [spencerwooo/onedrive-cf-index#30]
预览图片时，图片的高度有问题，绝大部分被盖住了，无法完整显示。
而点开查看大图是正常的。

![snipaste_20200911_012242](https://user-images.githubusercontent.com/20457790/92771261-4e8e1100-f3cd-11ea-894a-4a190999747b.png)

**Comment by lizkes** [comment]
更新，通过检查页面元素发现，padding-bottom的值是NAN
![snipaste_20200911_014148](https://user-images.githubusercontent.com/20457790/92774453-11774e00-f3d0-11ea-81d8-b05b0626e1c9.png)

问题就出在这里
https://github.com/spencerwooo/onedrive-cf-index/blob/04518d339e2ce8005f46ef64c1612454a724d589/src/fileView.js#L115-L116

**Comment by spencerwooo** [comment]
@lizkes 方便的话可以分享一下你的图片吗？我想看一下什么情况下 OneDrive 的图片获取不到长宽。还有应该很容易修好，但是我最近不太有时间，所以如果你方便的话可以直接发个 PR 我后面 merge 就好了。🧡

**Comment by lizkes** [comment]
原因找到了，是因为微软的API返回的image对象为空，根据官方文档的解释：如果该服务无法确定图像的宽度和高度，图像资源可能为空，看来需要加入对象为空情况下的处理逻辑。
我的图片存放在[这里](https://share.lizkes.com/历史资料/世界各国通史大全/世界历史地图)，所有图片都有这个问题。
顺便一提我使用的是世纪互联版onedrive。

![snipaste_20200911_020923](https://user-images.githubusercontent.com/20457790/92778562-de36be00-f3d3-11ea-9414-965c8d453c77.png)

**Comment by lizkes** [comment]
可以用请求缩略图的API来获取宽度跟高度，从而得到radio，我尝试写一个RP出来.

**Comment by lizkes** [comment]
Done

**Comment by Micraow** [comment]
现在还是有这个问题，我的图片是一个gif图片。
