### ISSUE TITLE
升级之后出现了问题

### ISSUE THREAD

**Issue by Micraow** [spencerwooo/onedrive-cf-index#34]
`{"code":"BadRequest","message":"Resource not found for the segment 'root:'.","innerError":{"date":"2020-09-21T12:20:30","request-id":"c4927bbb-97c4-4a6d-8816-22c9bf470cbe","client-request-id":"c4927bbb-97c4-4a6d-8816-22c9bf470cbe"}}`

我在升级代码后出现了问题，如果问题在于我的存储库，麻烦帮我看下。

**Comment by spencerwooo** [comment]
确实偶尔会遇到，但我也确实不知道原因在哪，因为刷新一下这个错误有时候就能解决。

**Comment by Micraow** [comment]
可是，我已经等了30分钟了

**Comment by Micraow** [comment]
我在想是否是我手误，复制粘贴代码时出了错，但我不能确定 ，config没变。
对了，我已经尝试build publish了两遍了。

**Comment by Micraow** [comment]
还有，之前的bug还没修好

**Comment by spencerwooo** [comment]
> 还有，之前的bug还没修好

最近比较忙，我也不是专职维护开源项目的，只能说抱歉了。

**Comment by Micraow** [comment]
这个也理解，不过我很想知道我的问题如何解决。

**Comment by LufsX** [comment]
> 这个也理解，不过我很想知道我的问题如何解决。

Revert 掉 PR #24 就好了

**Comment by spencerwooo** [comment]
Should be fixed by reverting PR #24. Thanks @LufsX.

**Comment by simonsmh** [comment]
@spencerwooo @LufsX 请测试一下如果使用`encodeURI`替代`encodeURIComponent`是否可以再次复现此问题？这样`config.base`中的`/`就不会被转译了，也许可以解决一部分的问题。还有，报issue最好给一下复现用的config和路径，哪有盲修的。

**Comment by spencerwooo** [comment]
@simonsmh 我在我当前部署的 <https://storage.spencerwoo.com> 这个域名下的站点之前偶尔也会出现这里提到的问题（就是访问某个路径出现 `Resource not found for the segment 'root:`），之后刷新一下又恢复正常。报错信息中出现的问题在于 `root` 路径未找到，所以我觉得确实可能是 PR #24 中引入的对 base 路径进行 `encodeURIComponent` 的操作导致的，因此我根据 @LufsX 的建议把这部分恢复为原有实现。

**Comment by spencerwooo** [comment]
`encodeURI` 我后面会试一下的，暂时先不对 root 路径进行处理。

**Comment by LufsX** [comment]
> `encodeURI` 我后面会试一下的，暂时先不对 base 路径进行处理。

测试了一下，`encodeURL` 没有问题，`encodeURIComponent ` 则复现

[encodeURL 的提交](https://github.com/LufsX/onedrive-cf-index/commit/c671cc57bf346fe842921140a723cd6cb89ef848)，对应[站点](https://storage.isteed.cc/)
[encodeURIComponent 的提交](https://github.com/LufsX/onedrive-cf-index/commit/c76aa0ba607fdd47264f3142351030526421029d)，对应[站点](https://tset.lufs.workers.dev/)

看起来没问题了 🤣
