### ISSUE TITLE
[Feature request (docs)] Documentation i18n.

### ISSUE THREAD

**Issue by Borber** [spencerwooo/onedrive-cf-index#35]
如题

**Comment by spencerwooo** [comment]
欢迎贡献。

**Comment by ChenYFan** [comment]
https://blog.cyfan.top/p/4fb070ca.html
不客气/捂脸

**Comment by spencerwooo** [comment]
> 这对一些使用者造成了一定的困扰，而且文档相当言简意赅。

个人认为当前 README 已经把关键配置叙述的很完整了，请问哪里还有需要详细说明的地方呢？@ChenYFan

**Comment by spencerwooo** [comment]
另外最近事情着实很多，没有时间增加文档内容，只能偶尔看看 PR 修修 bug，如果后面有时间了或者有我认为格式合理、配置清晰的中文文档贡献，我是很乐意添加中文文档支持的。

**Comment by ChenYFan** [comment]
Get OneDrive API Tokens这一步没有图文，而且没有考虑到不同版本的OneDrive【至少我写这篇文章时没有】并且Token生成繁琐里面有很多弯弯绕绕的坑【至少在我部署的时候踩了不少，英文文档没有写出足够的注意点】
