### ISSUE TITLE
[Bug] 缩略图功能报错

### ISSUE THREAD

**Issue by TTDARK** [spencerwooo/onedrive-cf-index#41]
按照 https://github.com/spencerwooo/onedrive-cf-index#all-other-features
链接的 https://github.com/heymind/OneDrive-Index-Cloudflare-Worker#%EF%B8%8F-%E7%BC%A9%E7%95%A5%E5%9B%BE
打开了`File.ReadWrite`权限，之后重新`wrangler publish`了一遍，但是缩略图链接打开之后会报错，不显示小图

在.jpg链接后面尝试加上
`?thumbnail=mediumSquare`
会跳转到 https://graph.microsoft.com/v1.0/me/drive/root:/img/xxxxxxx.jpg:/thumbnails/0/mediumSquare/content
之后打开的页面显示
```
 {

  "error": {
    "code": "InvalidAuthenticationToken",
    "message": "Access token is empty.",
    "innerError": {
      "date": "2020-10-27T19:52:45",
      "request-id": "4b445a2d-f13b-4d9e-b2d2-ca35d6d5b98d",
      "client-request-id": "4b445a2d-f13b-4d9e-b2d2-ca35d6d5b98d"
    }
  }
}
```

**Comment by spencerwooo** [comment]
为了能够按照相对路径渲染 Markdown 文件中的图片，我在图像 URL 参数后添加了 `?raw=true` 的参数解析，因此其他比如 `?thumbnail=mediumSquare` 的功能可能会受到影响，这个项目为了一些我个人认为更有用的功能进行了一些取舍，因此可能和原有项目的功能宣传有所差异。当然，缩略图这个功能还是可以实现的，因此后面如果有机会我会更新这个功能。同时也欢迎 PR 来更新这一问题。

**Comment by spencerwooo** [comment]
> 打开了 `File.ReadWrite` 权限...

另外这个功能和 `File.ReadWrite` 权限没有任何关系，我怀疑你看串行了。

**Comment by TTDARK** [comment]
> > 打开了 `File.ReadWrite` 权限...
> 
> 另外这个功能和 `File.ReadWrite` 权限没有任何关系，我怀疑你看串行了。

啊对是的，那个是上面上传用的。我看串了

**Comment by YuriSizuku** [comment]
> 为了能够按照相对路径渲染 Markdown 文件中的图片，我在图像 URL 参数后添加了 `?raw=true` 的参数解析，因此其他比如 `?thumbnail=mediumSquare` 的功能可能会受到影响，这个项目为了一些我个人认为更有用的功能进行了一些取舍，因此可能和原有项目的功能宣传有所差异。当然，缩略图这个功能还是可以实现的，因此后面如果有机会我会更新这个功能。同时也欢迎 PR 来更新这一问题。

希望可以实现这个功能，毕竟用作图床缩略图很实用的
