### ISSUE TITLE
APlayer、Dplayer 报错

### ISSUE THREAD

**Issue by wjy20030407** [spencerwooo/onedrive-cf-index#45]
![APlayer](https://i.loli.net/2020/11/06/xSEbcYBhl4iTg5O.png)
![DPlayer](https://i.loli.net/2020/11/06/fSpqyxPZhFX6CGc.png)

**Comment by spencerwooo** [comment]
May be related to recent PR #43

**Comment by spencerwooo** [comment]
cc @simonsmh
