### ISSUE TITLE
`itemNotFound` issue that may be related to PR #33 

### ISSUE THREAD

**Issue by ella-tj** [spencerwooo/onedrive-cf-index#47]
布署完成出现如下错误信息，不知道哪里出问题了？麻烦大佬帮忙看下，谢谢啦！
👷  Your Worker responded with: {"code":"itemNotFound","message":"The resource could not be found.","innerError":{"date":"2020-11-08T06:40:09","request-id":"3129ea8c-f0c2-4dcc-8df8-b83c6753ad4c","client-request-id":"3129ea8c-f0c2-4dcc-8df8-b83c6753ad4c"}}

**Comment by LufsX** [comment]
PR #33 的问题，[Revert](https://github.com/LufsX/onedrive-cf-index/commit/1acb86334cbb77d12bd41d344959cb51830dc903) 掉应该就能用了(

**Comment by spencerwooo** [comment]
@ella-tj 什么场景下出现的问题？是直接部署之后，访问线上地址出现的报错吗？

**Comment by spencerwooo** [comment]
> PR #33 的问题，[Revert](https://github.com/LufsX/onedrive-cf-index/commit/1acb86334cbb77d12bd41d344959cb51830dc903) 掉应该就能用了(

@LufsX PR #33 真的有问题吗？我当前部署的 Demo 没发现问题啊？

**Comment by ella-tj** [comment]
用@LufsX 的版本布署成功了，没有出错，谢谢大佬！

**Comment by spencerwooo** [comment]
@LufsX 方便提供一下 `itemNotFound` 的复现方法吗？以及 cc @beetcb

**Comment by ella-tj** [comment]
@spencerwooo 没错，是wrangler preview之后，就提示这行出错。

**Comment by beetcb** [comment]
[root](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_list_children?view=odsp-graph-online#list-children-of-a-driveitem-with-a-known-id)@spencerwooo 可能是部署的root作为索引目录？@ella-tj

**Comment by ella-tj** [comment]
不是，我是git clone项目，然后cd 项目里布署的，不是在root下布署的。

**Comment by beetcb** [comment]
nono，😊 我的意思是这里，是否是`/` ![Screenshot_20201109-103318_GitHub.png](https://user-images.githubusercontent.com/63141491/98494227-6c65de00-2277-11eb-9872-57587234c209.png)

**Comment by ella-tj** [comment]
@beetcb 跟这个没关系，base子目录也一样出错，我试过了。

**Comment by beetcb** [comment]
初步判断是 children api 没有 handle 好 [root](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_list_children?view=odsp-graph-online#list-children-in-the-root-of-the-current-users-drive)，请看看这两个测试：[root](https://drive.tcxz.cc/) [root/share](https://drive.tcxz.cc/share) @spencerwooo

**Comment by ella-tj** [comment]
@spencerwooo 能否增加挂载sharepoint的功能？谢谢

**Comment by spencerwooo** [comment]
> @spencerwooo 能否增加挂载sharepoint的功能？谢谢

新 feature request 请单独开 issue 讨论，谢谢。

**Comment by LufsX** [comment]
> @LufsX 方便提供一下 `itemNotFound` 的复现方法吗？以及 cc @beetcb

抱歉哈，我也不知道如复现，这个只是我部署临时的解决方法

**Comment by beetcb** [comment]
方便用这个 [patch](https://github.com/beetcb/onedrive-cf-index-CN/tree/patch-1) 测试一下吗，感谢

**Comment by beetcb** [comment]
> 方便用这个 [patch #49 PR49](https://github.com/beetcb/onedrive-cf-index-CN/tree/beetcb-patch-1-api-debug-purpose) 测试一下吗，感谢 @LufsX

直接 `wrangler dev` 可以看到 console 的输出

**Comment by LufsX** [comment]
> 方便用这个 [patch #49 PR49](https://github.com/beetcb/onedrive-cf-index-CN/tree/beetcb-patch-1-api-debug-purpose) 测试一下吗，感谢 @LufsX

等周末测试一下

**Comment by LufsX** [comment]
> 方便用这个 [patch #49 PR49](https://github.com/beetcb/onedrive-cf-index-CN/tree/beetcb-patch-1-api-debug-purpose) 测试一下吗，感谢 @LufsX

PR #49 可用

左 PR #49 ，右 未改动
![image](https://user-images.githubusercontent.com/33221883/99069929-3fecf180-25ea-11eb-9d8e-c94d63152ccd.png)

**Comment by spencerwooo** [comment]
明早我来 review 一下 PR #49，谢谢 @LufsX @beetcb
