### ISSUE TITLE
[Feature request] Mounting SharePoint

### ISSUE THREAD

**Issue by ella-tj** [spencerwooo/onedrive-cf-index#48]
能否增加挂载sharepoint的功能？ 这个功能很多人需要，麻烦大佬看下是否能实现，谢谢。

**Comment by spencerwooo** [comment]
我没用过 SharePoint，不知道具体怎么实现，可能需要大佬来帮忙了…

**Comment by beetcb** [comment]
不是大佬, 只是今天比较闲, 就对着文档实现了 sharePoint : 总体上讲跟 onedrive 区别不大, 只不过现在我不知道把它放到哪里好, 到底是再开一个 branch 还是在现有代码上修改呢? ( 我个人倾向前者, 应该不会有人同时挂载两种吧 ) @spencerwooo

**Comment by spencerwooo** [comment]
> 不是大佬, 只是今天比较闲  , 就对着文档实现了 [sharePoint](https://github.com/beetcb/onedrive-cf-index-CN/commit/1d5d99e62cf96bcfe0e6e9d58db8b7d95f5681a9) : 总体上讲跟 onedrive 区别不大, 只不过现在我不知道把它放到哪里好, 我们到底是再开一个 branch 还是在现有代码上修改呢? ( 我个人倾向前者, 应该不会有人同时挂载两种吧 ) @spencerwooo

我已经赶不上你提 PR 的速度了 :sob:，有时间马上看，我倾向于在项目基础上改，要不然 SharePoint 部署还得单独再维护一个代码库。可以在 config 里面定一个参数来开 OneDrive 普通 / OneDrive 世纪互联 / SharePoint 三种模式？Maybe，我也不知道我还没看你 SharePoint 的具体代码都改啥了…

**Comment by beetcb** [comment]
害! 还不是你比较忙。不过还有一个问题: 如果用户同时开启 onedrive 和 sharePoint 怎么处理, 前端可切换 or 只允许一种挂载 @spencerwooo

**Comment by spencerwooo** [comment]
> 害! 还不是你比较忙。不过还有一个问题: 如果用户同时开启 onedrive 和 sharePoint 怎么处理, 前端可切换 or 只允许一种挂载 @spencerwooo

```js
const ModeEnum = { ONEDRIVE_INTER: 1, ONEDRIVE_CN: 2, SHAREPOINT: 3 }
```

开了 SharePoint 就 override 掉 OneDrive 普通？

**Comment by beetcb** [comment]
这样吧，让用户设 ModeEnum ( 1 2 3 ), 我们注释说明三种类型

**Comment by spencerwooo** [comment]
@ella-tj ping 一下
