### ISSUE TITLE
/Public目录下第一层能显示，而第二层（点击第一层文件夹）则报"Error 1101"

### ISSUE THREAD

**Issue by C-rey** [spencerwooo/onedrive-cf-index#50]
action无报错，第一层README.md文件能点进去，而第一层的文件夹点进去就报错"Error 1101"

**Comment by beetcb** [comment]
> action无报错，第一层README.md文件能点进去，而第一层的文件夹点进去就报错"Error 1101"

方便截图cf worker编辑界面的预览那一栏下面console的报错吗

**Comment by C-rey** [comment]
为了复现，n个操作后事情变成了打开worker网址就报错"Error 1101"，action无报错，观察不到firebase写入（只有初始的几项），在修改成加密后（AUTH_ENABLED = true），打开网址能输入用户名密码，确认后仍然"Error 1101"，快速编辑没发现特别的，服务器500。
![Uploading Snipaste_2020-11-10_21-11-47.png…]()
凭记忆出现过worker. apierror. unknown(Code: 10013)或router错误，红色报错中含有CF账户id。
另，之前CF环境变量中没点击加密，出现过action后CF环境变量消失的情况，不知其中关系。
