### ISSUE TITLE
[Bug fix!] Use Cloudflare KV instead of Firebase

### ISSUE THREAD

**Issue by ChenYFan** [spencerwooo/onedrive-cf-index#54]
<https://blog.cyfan.top/p/4fb070ca.html>，有位同学提醒我KV已经免费【Free1GB空间】了。
我想，使用KV显然比FireBase更加容易，Spencerwooo能否试试KV？

**Comment by ChenYFan** [comment]
![image](https://user-images.githubusercontent.com/53730587/99781270-9ad69980-2b52-11eb-9580-85867febb1fa.png)

**Comment by spencerwooo** [comment]
谢谢提醒，后面有时间会加上直接使用 KV 免费额度存储的支持。
