### ISSUE TITLE
Any idea how to make this work with Dropbox instead of OneDrive?

### ISSUE THREAD

**Issue by bnichs5** [spencerwooo/onedrive-cf-index#55]
Hey Man. Great Work!

Do you happen to know if its possible to create a Dropbox cloudflare index just like this?

Thanks so much!

**Comment by spencerwooo** [comment]
Provided that Dropbox has enough API support like OneDrive or Google Drive, I don't see why we can't implement one. After a bit of searching I found similar projects like: [alx-xlx/goindex](https://github.com/alx-xlx/goindex) which support indexing Google Drive, but I didn't find any existing project that supports Dropbox.

**Comment by spencerwooo** [comment]
This is obviously out of the scope of this project, so I'm going to close this, but feel free to comment if you find one that supports Dropbox :smiley: .
