### ISSUE TITLE
APlayer、DPlayer 首次加载完后再载入其他文件出现错误

### ISSUE THREAD

**Issue by wjy20030407** [spencerwooo/onedrive-cf-index#57]
![APlayer](https://i.loli.net/2020/11/23/mokt4j2XucrJs6b.png)
![DPlayer](https://i.loli.net/2020/11/23/e3JYOE5Wjf8yZ7m.png)

**Comment by spencerwooo** [comment]
Ok...so apparently PR #46 still has some issues. cc @simonsmh

**Comment by simonsmh** [comment]
https://github.com/simonsmh/onedrive-cf-index-1/blob/0e977631c5ec8826aae35ff792a6afde0f9427ad/src/fileView.js#L128
https://github.com/simonsmh/onedrive-cf-index-1/blob/0e977631c5ec8826aae35ff792a6afde0f9427ad/src/fileView.js#L149

**Comment by beetcb** [comment]
i believe [this](https://github.com/spencerwooo/onedrive-cf-index/compare/master...beetcb:patch-1) can avoid a/v player duplicate declaration and closing this, too tiny to create a PR
