### ISSUE TITLE
使用Cloudflare KV几个问题

### ISSUE THREAD

**Issue by weiyunkj666** [spencerwooo/onedrive-cf-index#58]
wrangler.toml中的preview_id = ""应该填什么？我使用的是GitHub Actions

使用Firebase 数据库时在Cloudflare [Workers填写在大于1KB的变量时按照这个教程可以解决https://github.com/spencerwooo/onedrive-cf-index/issues/16

但现在使用Cloudflare KV不知道怎么操作了。。。希望大佬指点迷津

**Comment by spencerwooo** [comment]
**第一个问题：**`preview_id` 是用于本地预览的，如果在生成那一步没有传入 `--preview` 的话是不会生成 `preview_id` 的，所以不写 `preview_id` 这个 field **并不影响部署**，只是会影响本地预览。

![image](https://user-images.githubusercontent.com/32114380/100172922-5bb69880-2f04-11eb-8723-3e0c7881521f.png)

这一步跟 GitHub Actions 也没关系，因为这里两个 ID 都是固定的，直接写入 `wrangler.toml` 即可。

你可以本地尝试跑一跑带 `--preview` 和不带 `--preview` 两个命令，看看输出就知道怎么回事了。

**第二个问题：** 一样可以用 Cloudflare KV Storage 来存这个 Token。

**Comment by weiyunkj666** [comment]
好的，第一个问题只影响本地预览，不碍事，不填了

第二个问题，谢谢大佬了，等着您

**Comment by spencerwooo** [comment]
首先还是一样的操作，拿到 `refresh_token` 之后，在 Cloudflare Workers -> KV 里面的 `BUCKET` 中创建一个新的 `entry` 就叫做 `access_token`，然后把你拿到的 `refresn_token` 粘进去：

![image](https://user-images.githubusercontent.com/32114380/100174236-fe701680-2f06-11eb-9958-655d60da8f1d.png)

之后修改代码，在 `./src/auth/onedrive.js` 里面加一个获取 `refresh_token` 的代码：

```js
// ./src/auth/onedrive.js

// ...
export async function getAccessToken() {
  const timestamp = () => {
    return Math.floor(Date.now() / 1000)
  }

 const refresh_token = await BUCKET.get('refresh_token')

  // 之后所有的 config.refresh_token 都直接改为 refresh_token
  // ...
}
```

这样应该就可以了，顺便还要把其他原有定义了 `REFRESH_TOKEN` 的地方删掉（比如 `./src/config/default.js` 里面的 `refresh_token: REFRESH_TOKEN,` 一行）。

**Comment by Micraow** [comment]
好像不行，有错误 Error 1101 Ray ID: 5f9a7b6fb81d04f7 • 2020-11-29 07:05:46 UTC
Worker threw exception

**Comment by Micraow** [comment]
已发送邀请，请帮我检查，谢谢！

**Comment by SakuraPuare** [comment]
> 首先还是一样的操作，拿到 `refresh_token` 之后，在 Cloudflare Workers →KV 里面的 `BUCKET` namespace 中创建一个新的 `entry` 就叫做 `access_token`，然后把你拿到的 `refresn_token` 粘进去：
> 
> ![image](https://user-images.githubusercontent.com/32114380/100174236-fe701680-2f06-11eb-9958-655d60da8f1d.png)
> 
> 之后修改代码，在 `./src/auth/onedrive.js` 里面加一个获取 `refresh_token` 的代码：
> 
> ```js
> // ./src/auth/onedrive.js
> 
> // ...
> export async function getAccessToken() {
>   const timestamp = () => {
>     return Math.floor(Date.now() / 1000)
>   }
> 
>   const refresh_token = await BUCKET.get('refresh_token')
> 
>   // 之后所有的 config.refresh_token 都直接改为 refresh_token
>   // ...
> }
> ```
> 
> 这样应该就可以了，顺便还要把其他原有定义了 `REFRESH_TOKEN` 的地方删掉（比如 `./src/config/default.js` 里面的 `refresh_token: REFRESH_TOKEN,` 一行）。

key应该是` refresh_token`

**Comment by xwwbest** [comment]
./src/auth/onedrive.js 72:22
Module parse failed: Identifier 'getAccessToken' has already been declared (72:22)
You may need an appropriate loader to handle this file type.
|
| // ...
> export async function getAccessToken() {
|   const timestamp = () => {
|     return Math.floor(Date.now() / 1000)
 @ ./src/index.js 4:0-59 55:28-42 57:42-51
Error: webpack returned an error. You may be able to resolve this issue by running npm install.

按教程操作之后提示这

**Comment by SakuraPuare** [comment]
> ./src/auth/onedrive.js 72:22
> Module parse failed: Identifier 'getAccessToken' has already been declared (72:22)
> You may need an appropriate loader to handle this file type.
> |
> | // ...
> 
> > export async function getAccessToken() {
> > |   const timestamp = () => {
> > |     return Math.floor(Date.now() / 1000)
> > @ ./src/index.js 4:0-59 55:28-42 57:42-51
> > Error: webpack returned an error. You may be able to resolve this issue by running npm install.
> 
> 按教程操作之后提示这

还要把其他原有定义了 REFRESH_TOKEN 的地方删掉
比如 ./src/config/default.js 里面的 refresh_token: REFRESH_TOKEN, 一行

**Comment by xwwbest** [comment]
> fa

已经删了

**Comment by SakuraPuare** [comment]
>Error: webpack returned an error. You may be able to resolve this issue by running npm install.

试试`npm install`？

**Comment by xwwbest** [comment]
./src/auth/onedrive.js 72:22
Module parse failed: Identifier 'getAccessToken' has already been declared (72:22)
You may need an appropriate loader to handle this file type.
|
| // ...
> export async function getAccessToken() {
|   const timestamp = () => {
|     return Math.floor(Date.now() / 1000)
 @ ./src/index.js 4:0-59 55:28-42 57:42-51
Error: webpack returned an error. You may be able to resolve this issue by running npm install.

试过了，还是这样

**Comment by SakuraPuare** [comment]
> ./src/auth/onedrive.js 72:22
> Module parse failed: Identifier 'getAccessToken' has already been declared (72:22)
> You may need an appropriate loader to handle this file type.
> |
> | // ...
> 
> > export async function getAccessToken() {
> > |   const timestamp = () => {
> > |     return Math.floor(Date.now() / 1000)
> > @ ./src/index.js 4:0-59 55:28-42 57:42-51
> > Error: webpack returned an error. You may be able to resolve this issue by running npm install.
> 
> 试过了，还是这样

贴一下`onedrive.js`

**Comment by xwwbest** [comment]
import config from '../config/default'

/**
 * Get access token for microsoft graph API endpoints. Refresh token if needed.
 */
export async function getAccessToken() {
  const timestamp = () => {
    return Math.floor(Date.now() / 1000)
  }

  // Fetch access token
  const data = await BUCKET.get('onedrive', 'json')
  if (data && data.access_token && timestamp() < data.expire_at) {
    console.log('Fetched token from storage.')
    return data.access_token
  }

  // Token expired, refresh access token with Microsoft API. Both international and china-specific API are supported
  const oneDriveAuthEndpoint = `${config.apiEndpoint.auth}/token`

  const resp = await fetch(oneDriveAuthEndpoint, {
    method: 'POST',
    body: `client_id=${config.client_id}&redirect_uri=${config.redirect_uri}&client_secret=${config.client_secret}
    &refresh_token=${config.refresh_token}&grant_type=refresh_token`,
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded'
    }
  })
  if (resp.ok) {
    console.info('Successfully refreshed access_token.')
    const data = await resp.json()

    // Update expiration time on token refresh
    data.expire_at = timestamp() + data.expires_in

    await BUCKET.put('onedrive', JSON.stringify(data))
    console.info('Successfully updated access_token.')

    // Finally, return access token
    return data.access_token
  } else {
    // eslint-disable-next-line no-throw-literal
    throw `getAccessToken error ${JSON.stringify(await resp.text())}`
  }
}

/**
 * Get & store siteID for finding sharepoint resources
 *
 * @param {string} accessToken token for accessing graph API
 */
export async function getSiteID(accessToken) {
  let data = await BUCKET.get('sharepoint', 'json')
  if (!data) {
    const resp = await fetch(`${config.apiEndpoint.graph}${config.baseResource}?$select=id`, {
      headers: {
        Authorization: `bearer ${accessToken}`
      }
    })
    if (resp.ok) {
      data = await resp.json()
      console.log('Got & stored site-id.')
      await BUCKET.put('sharepoint', JSON.stringify({ id: data.id }))
    }
  }
  return data.id
}

// ./src/auth/onedrive.js

// ...
export async function getAccessToken() {
  const timestamp = () => {
    return Math.floor(Date.now() / 1000)
  }

  const refresh_token = await BUCKET.get('refresh_token')

  // 之后所有的 config.refresh_token 都直接改为 refresh_token
  // ...
}

**Comment by SakuraPuare** [comment]
> import config from '../config/default'
> 
> /**
> 
> * Get access token for microsoft graph API endpoints. Refresh token if needed.
>   */
>   export async function getAccessToken() {
>   const timestamp = () => {
>   return Math.floor(Date.now() / 1000)
>   }
> 
> // Fetch access token
> const data = await BUCKET.get('onedrive', 'json')
> if (data && data.access_token && timestamp() < data.expire_at) {
> console.log('Fetched token from storage.')
> return data.access_token
> }
> 
> // Token expired, refresh access token with Microsoft API. Both international and china-specific API are supported
> const oneDriveAuthEndpoint = `${config.apiEndpoint.auth}/token`
> 
> const resp = await fetch(oneDriveAuthEndpoint, {
> method: 'POST',
> body: `client_id=${config.client_id}&redirect_uri=${config.redirect_uri}&client_secret=${config.client_secret} &refresh_token=${config.refresh_token}&grant_type=refresh_token`,
> headers: {
> 'Content-Type': 'application/x-www-form-urlencoded'
> }
> })
> if (resp.ok) {
> console.info('Successfully refreshed access_token.')
> const data = await resp.json()
> 
> ```
> // Update expiration time on token refresh
> data.expire_at = timestamp() + data.expires_in
> 
> await BUCKET.put('onedrive', JSON.stringify(data))
> console.info('Successfully updated access_token.')
> 
> // Finally, return access token
> return data.access_token
> ```
> 
> } else {
> // eslint-disable-next-line no-throw-literal
> throw `getAccessToken error ${JSON.stringify(await resp.text())}`
> }
> }
> 
> /**
> 
> * Get & store siteID for finding sharepoint resources
> * @param {string} accessToken token for accessing graph API
>   */
>   export async function getSiteID(accessToken) {
>   let data = await BUCKET.get('sharepoint', 'json')
>   if (!data) {
>   const resp = await fetch(`${config.apiEndpoint.graph}${config.baseResource}?$select=id`, {
>   headers: {
>   Authorization: `bearer ${accessToken}`
>   }
>   })
>   if (resp.ok) {
>   data = await resp.json()
>   console.log('Got & stored site-id.')
>   await BUCKET.put('sharepoint', JSON.stringify({ id: data.id }))
>   }
>   }
>   return data.id
>   }
> 
> // ./src/auth/onedrive.js
> 
> // ...
> export async function getAccessToken() {
> const timestamp = () => {
> return Math.floor(Date.now() / 1000)
> }
> 
> const refresh_token = await BUCKET.get('refresh_token')
> 
> // 之后所有的 config.refresh_token 都直接改为 refresh_token
> // ...
> }

加语句没加，下面删也没删。
你用我库里的吧。。。
[onedrive.js](https://github.com/SakuraPuare/mdui-onedrive-cf-index/blob/master/src/auth/onedrive.js)

**Comment by xwwbest** [comment]
阿，不知道阿，就按教程搞得

**Comment by SakuraPuare** [comment]
> 阿，不知道阿，就按教程搞得

你这完全不懂JavaScript。。
把上面的commit删一下吧

**Comment by xwwbest** [comment]
大佬等一下。现在还是不行

**Comment by xwwbest** [comment]
大佬等一下。现在还是不行

**Comment by SakuraPuare** [comment]
> 大佬等一下。现在还是不行

有问题开issue，把上面无关commit删一下

**Comment by xwwbest** [comment]
大佬，用你刚刚给的库部署好了。一样的操作，不晓得啥情况。
