### ISSUE TITLE
新功能

### ISSUE THREAD

**Issue by Micraow** [spencerwooo/onedrive-cf-index#59]
对于 doc、ppt 和微软系列的文档，表格，幻灯片文档，是否可以嵌入一些 HTML 代码，使程序可以预览他们，这个应该是可以实现的，因为我在 oneindex 里面已经看到了这个功能的实现。

可以参考：
https://docs.microsoft.com/zh-cn/graph/api/driveitem-preview?view=graph-rest-1.0

**Comment by spencerwooo** [comment]
你不是提过这个了吗？

**Comment by spencerwooo** [comment]
Dup #20
