### ISSUE TITLE
分页功能有问题

### ISSUE THREAD

**Issue by Micraow** [spencerwooo/onedrive-cf-index#60]
已确认是普遍的bug

描述：在safari中，Next Prev按钮无法点击，其它平台上点击有1101未知错误

问题模块：分页

**Comment by spencerwooo** [comment]
cc @beetcb

**Comment by beetcb** [comment]
![quickfik](https://user-images.githubusercontent.com/63141491/100541643-3f0dbe00-3280-11eb-9015-1939775b3b95.png)

**Comment by beetcb** [comment]
My bad, change one specifier would fix :

[this line](https://github.com/spencerwooo/onedrive-cf-index/blob/b6706a892e305425a833747f7b4bb181b683028a/src/index.js#L91) -> ![new specifier](https://user-images.githubusercontent.com/63141491/100541679-695f7b80-3280-11eb-8edb-47e19798d3c7.png)

**Comment by spencerwooo** [comment]
Nope, safari still not working.

**Comment by beetcb** [comment]
i tested [this page](https://storage.spencerwoo.com/%F0%9F%A5%9F%20Some%20test%20files/Pagination/), the 'next' link works fine on those devices. it's weird
- [x] my macOS Mojave safari
- [x] mac safari on `browserstack.com` devices
- [x] iphone safari on `browserstack.com` devices

**Comment by beetcb** [comment]
@Micraow safari 还是无法点击吗？帮我看看，我研究一下

**Comment by spencerwooo** [comment]
@beetcb 我在 iPhone 上点不了…iOS 14.3, iPhone 12

**Comment by beetcb** [comment]
我试试把事件触发处理移到 js 中去，可能是这 onClick 的问题
```html
<a class="next" href="pagination?page=2" onclick="handlePagination(1)">NEXT <i class="fas fa-angle-right" style="font-size: 8px;"></i></a>
```

**Comment by beetcb** [comment]
再试试能点🐔吗 http://drive.tcxz.cc/pagination%20test/ 😇

**Comment by spencerwooo** [comment]
> 再试试能点🐔吗 http://drive.tcxz.cc/pagination%20test/ 😇

并不能🌚

**Comment by beetcb** [comment]
![OOpRj.gif](https://user-images.githubusercontent.com/63141491/103552244-8eca4f80-4ee6-11eb-9d3b-242c0a2e882f.gif)

**Comment by spencerwooo** [comment]
> ![OOpRj.gif](https://user-images.githubusercontent.com/63141491/103552244-8eca4f80-4ee6-11eb-9d3b-242c0a2e882f.gif)
> 改了 css , 上面链接再试试把, 麻烦了  @spencerwooo

@beetcb 还是不好使…

**Comment by beetcb** [comment]
我现在确定是 flex 布局的问题, 换成 grid 应该是行了 http://drive.tcxz.cc/pagination%20test/

**Comment by spencerwooo** [comment]
> 我现在确定是 flex 布局的问题, 换成 grid 应该是行了 http://drive.tcxz.cc/pagination%20test/ @spencerwooo

哈，确实好使了，玄学 CSS

**Comment by hezhijie0327** [comment]
3e26413160a4047350ee16df77cad9e91c16683b
感觉还是有点问题包括 [Demo 页面](https://storage.spencerwoo.com/🥟%20Some%20test%20files/Pagination) 也无法实现下一页，且`CSS`貌似也出现了偏移问题。
<img width="840" alt="截图 2021-01-10 20 56 29" src="https://user-images.githubusercontent.com/58100052/104123596-0c7ad900-5387-11eb-8d9d-c643f47bbae9.png">

**Comment by beetcb** [comment]
提 PR 时候漏掉了, 这一行 [原](https://github.com/spencerwooo/onedrive-cf-index/blob/3e26413160a4047350ee16df77cad9e91c16683b/src/render/htmlWrapper.js#L8) 应该是 [改](https://github.com/beetcb/onedrive-cf-index-CN/blob/4e739bfa43047ba72702b15cfb499da07b4829c3/src/render/htmlWrapper.js#L9)

还有 css 应该改为：
```css
.paginate-container {
    margin-top: 1.5rem;
    display: grid;
    justify-content: space-between;
    grid-template-columns: repeat(3, auto);
}
```

抱歉我嫌麻烦没有拿 PR 测试  @spencerwooo
