### ISSUE TITLE
如何绑定域名

### ISSUE THREAD

**Issue by Micraow** [spencerwooo/onedrive-cf-index#64]
如题，我想知道如何像示例站点那样，将workers.dev域名绑定到自己的域名上，望指导。
另听说workers可自选节点(可能是由于这，所以storage.spencerwooo.com比我的快)，那怎么选呢？我按教程绑定了workers，改了A记录。刚改完，可用，第二天又有问题。
请指导我使用香港节点
谢谢

**Comment by beetcb** [comment]
1. 自定 domain：
     1. 添加域名到 cf ，DNS 记录有两个选择
      - `CNAME`: name.your.workers.dev
      - `A`: ping 一下你的 worker 地址，找到可用的 ip 地址（可添加多条 A 记录）
    
      2. 然后在 worker 栏下 Add Route：
        `sub.domain.com/*` 或 `domain.com/*` 根据你的 DNS 记录，选中你的 worker 就 ok。
2. 关于自选节点：
没用过，google 后感觉稍显麻烦，且不稳定；优点似乎是不需要把 cf 作为 DNS 服务商。不过你可以继续尝试，如果成功，可以作为这个 issue 的补充帮助其他人
