### ISSUE TITLE
中转下载与文件预览冲突

### ISSUE THREAD

**Issue by Micraow** [spencerwooo/onedrive-cf-index#65]
如题。

举个例子，我有aaa.jpg 那么它的网络地址应该是

nnn.nnn.workers.dev/aaa.jpg

这时会进入预览界面，而非下载，但这可以接受。

然而，我要中转下载，
输入

nnn.nnn.workers.dev/aaa.jpg?proxied

它还是显示预览界面，这令人生气，希望改一下，谢谢。

**Comment by beetcb** [comment]
所有预览都可暂时关闭，通过 `raw` 参数：
```js
nnn.nnn.workers.dev/aaa.jpg?raw=true&proxied
```

**Comment by spencerwooo** [comment]
Will add appropriate documentation for this.
