### ISSUE TITLE
cache功能没有利用

### ISSUE THREAD

**Issue by Micraow** [spencerwooo/onedrive-cf-index#66]
在原版中，小图片，小文件预览都是走缓存的，包括整式缓存和流式缓存。但在这里，所有预览无论如何，走的都是Microsoft Graph Download URL，很慢，希望改成从cloudflare缓存读取

**Comment by spencerwooo** [comment]
原版本身也没有预览啊，不知道对比何在？另外什么是「整式缓存和流式缓存」？

**Comment by Micraow** [comment]
抱歉，我的表述有误。说输入那个文件链接之后，可以直接看见文件内容，比如说
https://storage.idx0.workers.dev/Images/abc.jpeg
会直接把图片给显示出来。

然后它原版中有一个缓存功能。worker会通过msgraph 下载链接把文件内容缓存到cloudflare 云端，这样就会很快。

整式缓存是指把整个文件给缓存下来。
流式缓存应该就是把大文件缓存点，然后传给用户，再缓存一点再发给用户。

**Comment by Micraow** [comment]
https://github.com/heymind/OneDrive-Index-Cloudflare-Worker#%EF%B8%8F-%E7%BC%93%E5%AD%98%E5%8A%9F%E8%83%BD

**Comment by beetcb** [comment]
我感觉你的大概意思就是把 `?proxied` 的功能应用到预览里面？

**Comment by beetcb** [comment]
> 我感觉你的大概意思就是把 `?proxied` 的功能应用到预览里面？

如果是这个需求，我的设想是可以通过在配置里面加个 
```js
cachePreview: true 
```
然后在 [这里](https://github.com/spencerwooo/onedrive-cf-index/blob/5e829ad374153cea2eae393c23632b1cd335fc70/src/files/load.js#L80) 加一条 else if 用来考虑这种情形，只不过预览那边不知道是否支持这种 cf 缓存的链接

**Comment by Micraow** [comment]
chunk缓存的话，好像和代理下载是一样的，但整个文件缓存这种又和代理下载不大同，整个缓存有正确的Content-Length
chunk和代理下载没有

我不太懂js，因为我学的是python ，这里把有关代码贴一下

**Comment by Micraow** [comment]
https://github.com/heymind/OneDrive-Index-Cloudflare-Worker/blob/master/index.js

207-292行

**Comment by beetcb** [comment]
> chunk缓存的话，好像和代理下载是一样的，但整个文件缓存这种又和代理下载不大同，整个缓存有正确的Content-Length
> chunk和代理下载没有
> 
> 我不太懂js，因为我学的是python ，这里把有关代码贴一下

对的，这也就是为什么之前的 issue #63 是无法实现的，设置了 `content-type: chunk` 的 header 是无法设置 `content-length` 的；再说这个 header 是 cf 设定的，我们无法干预

**Comment by Micraow** [comment]
这个我知道了，但缓存预览功能还是值得做出来的

它下载速度基本上1m 美妙

**Comment by Micraow** [comment]
每秒
