### ISSUE TITLE
400 errors in deployment

### ISSUE THREAD

**Issue by lem0nb** [spencerwooo/onedrive-cf-index#67]
` Built successfully, built project size is 24 KiB.
Error: Something went wrong! Status: 400 Bad Request, Details {
  "result": null,
  "success": false,
  "errors": [
    {
      "code": 10021,
      "message": "Uncaught ReferenceError: REFRESH_TOKEN is not defined\n  at line 1\n  at line 1 in t\n  at line 1\n  at line 1\n"
    }
  ],
  "messages": []
}`

Please help me. Thank you!

**Comment by spencerwooo** [comment]
I'm assuming this is now working?
