### ISSUE TITLE
CF 创建 KV 报错

### ISSUE THREAD

**Issue by fengzhao** [spencerwooo/onedrive-cf-index#69]
![image](https://user-images.githubusercontent.com/6206340/103284571-8b325680-4a16-11eb-8ec0-19b138577f36.png)

**Comment by spencerwooo** [comment]
"Authentication error"：认证失败。我认为不是本项目的问题，请检查自己的 wrangler 登录配置。

**Comment by fengzhao** [comment]
> "Authentication error"：认证失败。我认为不是本项目的问题，请检查自己的 wrangler 登录配置。

已经解决 ，谢谢
