### ISSUE TITLE
能不能在底栏加上用户侧信息？

### ISSUE THREAD

**Issue by fengzhao** [spencerwooo/onedrive-cf-index#70]
能不能在底栏加上用户侧信息？譬如访客IP，当前CDN节点？

**Comment by fengzhao** [comment]
https://blog.cyfan.top/p/a7d0d7f8.html

**Comment by spencerwooo** [comment]
不能，我认为很 annoying 以及 disturbing，如果一定要加，建议在自己的 fork 版本上面加。
