### ISSUE TITLE
请问如何将自己自定义的css应用到onedrive-cf-index？

### ISSUE THREAD

**Issue by Soys** [spencerwooo/onedrive-cf-index#75]
不是特别懂，要将自己更改的css样式应用，具体需要怎么做？

**Comment by spencerwooo** [comment]
在 `htmlWrapper.js` 里面有引用 CSS 的地方：https://github.com/spencerwooo/onedrive-cf-index/blob/master/src/render/htmlWrapper.js#L39

```html
<link href="https://cdn.jsdelivr.net/gh/spencerwooo/onedrive-cf-index@${COMMIT_HASH}/themes/spencer.css" rel="stylesheet">
```

其中的 `COMMIT_HASH`，也就是最新 commit 提交的哈希，在同一个文件的前面有定义：https://github.com/spencerwooo/onedrive-cf-index/blob/master/src/render/htmlWrapper.js#L3

```js
const COMMIT_HASH = '5d7579fcfb4729fcb855110c5f0ed5488d1d0d44'
```

你需要修改的就是这两个地方，也就是：

1. 在自己的仓库中修改 `spencer.css` 或者创建新的 `xxx.css`，按照自己的需要修改 CSS 内容
2. 在自己的仓库中修改 `htmlWrapper.js` 里面的引用路径，让 `htmlWrapper.js` 引用自己的 CSS 文件
3. 在自己的仓库中修改 `htmlWrapper.js` 里面的 `COMMIT_HASH` 为自己 commit 对应的值

再进行部署即可。
