### ISSUE TITLE
缩略图 InvalidAuthenticationToken  Access token is empty

### ISSUE THREAD

**Issue by shzxm** [spencerwooo/onedrive-cf-index#79]
图片文件 使用略缩图功能 出现报错
访问
https://onedriveshzxm.shzxm.workers.dev/about/about.jpg
访问略缩图
https://onedriveshzxm.shzxm.workers.dev/about/about.jpg?thumbnail=mediumSquare
出现报错
{
  "error": {
    "code": "InvalidAuthenticationToken",
    "message": "Access token is empty.",
    "innerError": {
      "date": "2021-01-06T19:28:01",
      "request-id": "f836b105-6e21-4bf7-ae48-06d5cfa26ce1",
      "client-request-id": "f836b105-6e21-4bf7-ae48-06d5cfa26ce1"
    }
  }
}

权限已经检查过了
![image](https://user-images.githubusercontent.com/9905297/103811952-b3662900-5098-11eb-949f-37f12fd6f7e2.png)

不知道现在是不是支持这个功能

如果不能 希望作者增加更新

**Comment by spencerwooo** [comment]
了解，缩略图功能确实有 bug。另外，如果要在别处引用图片，可以暂时把图片的直链 URL `https://xxx.xxx` 后面加上参数 `?raw` 来进行显示。

**Comment by shzxm** [comment]
> 另外，如果要在别处引用图片，可以暂时把图片的直链网址`https://xxx.xxx`后面加上参数`?raw`来进行显示。

现在直接复制图片链接.默认出来就是原图.可以使用.只是 略缩图失效了.不知道原因

**Comment by beetcb** [comment]
报错容易被重定向给误导，经尝试实际报错是 item not found: 

![image](https://user-images.githubusercontent.com/63141491/104126378-245a5900-5397-11eb-847e-9be4a10c25d8.png)

应该是 api 写错了 ...
