### ISSUE TITLE
[求助] 編譯成功 但 CF未顯示部署 以及打開錯誤

### ISSUE THREAD

**Issue by Borber** [spencerwooo/onedrive-cf-index#85]
倉庫地址: https://github.com/Borber/onedrive-cf-index/

使用github action 編譯:https://github.com/Borber/onedrive-cf-index/actions

使用E5帳號,REFRESH_TOKEN過長 所以參考 #16 使用 firebaseio 

訪問鏈接爲: https://***.firebaseio.com/auth/refresh_token.json 
    返回結果格式 "REFRESH_TOKEN" 

編譯結果: https://pastebin.ubuntu.com/p/dMZTCGJFdT/
以及CF並未更新部署時間

worker 地址: https://onedrive.borber.workers.dev/  打開錯誤
調試時報錯: https://pastebin.ubuntu.com/p/RDwCNhTKBK/

![image](https://user-images.githubusercontent.com/30563826/104190695-6cd94b80-5457-11eb-887c-4ba5176de8c1.png)

環境變量應該配置無誤

**Comment by Borber** [comment]
![image](https://user-images.githubusercontent.com/30563826/104198598-6223b400-5461-11eb-8044-6c27e4e5cec6.png)
![image](https://user-images.githubusercontent.com/30563826/104198638-6ea80c80-5461-11eb-99f0-5e810bb0eb86.png)

CF測試 token 請求報錯

**Comment by spencerwooo** [comment]
> 使用E5帳號,REFRESH_TOKEN過長 所以參考 #16 使用 firebaseio

尝试一下 https://github.com/spencerwooo/onedrive-cf-index/issues/58 提到的方法？就是说用 KV 而不是 Firebase 存 Token。

**Comment by Borber** [comment]
> > 使用E5帳號,REFRESH_TOKEN過長 所以參考 #16 使用 firebaseio
> 
> 尝试一下 #58 提到的方法？就是说用 KV 而不是 Firebase 存 Token。

OK 搞定了

**Comment by spencerwooo** [comment]
耶，垃圾 Firebase 石锤
