### ISSUE TITLE
试图调整页面宽度

### ISSUE THREAD

**Issue by aozaki-kuro** [spencerwooo/onedrive-cf-index#89]
大佬您好，我在部署该项目后发现过长的文件名会导致页面格式错乱
如图：
![image](https://user-images.githubusercontent.com/28428951/105046499-206bbc80-5aa4-11eb-8975-2f57531d0810.png)

换行后导致文件大小一栏也参差不齐，故试图调整页面宽度。

查看`themes/spencer.css`后发现
```
.container,
.paginate-container {
  width: calc(100% - 40px);
  max-width: 800px;
  margin: 0 auto;
}
```

对`max-width: 800px;`进行调整至1500px并修改`commit HASH`，部署后没有变化。

故想询问操作是否正确？谢谢！

**Comment by spencerwooo** [comment]
如果方便的话请提供一下测试页面方便我这边进行测试，另外也请检查一下引用的 CSS 文件里面确实有修改的内容。

**Comment by aozaki-kuro** [comment]
您好！在看到您的提示，重新检查代码后发现
在`src/render/htmlWrapper.js`除了需要修改`COMMIT_HASH`，还需要将下方html代码部分引用的jsdelivr地址改成自己的repo
重新部署后成功反映出修改（不好意思真的是新手小白）

另外就是文件名过长时产生的样式错乱，您希望进一步调整测试吗？我可以将宽度回滚过去

**Comment by sengoku-f** [comment]
可以添加 `css` 让超出的文字隐藏掉
```css
overflow:hidden; //超出的文本隐藏
text-overflow:ellipsis; //溢出用省略号显示
white-space:nowrap; //溢出不换行
width: calc(100% - 5rem);//限制宽度
```
![image](https://user-images.githubusercontent.com/31064651/105691189-e1bc8300-5f37-11eb-8480-b9472c43627d.png)

**Comment by 0wQ** [comment]
```
div.path,
a.item {
  word-break: break-all;
}
span.size {
  white-space: nowrap;
}
div.items > div {
  min-width: 280px !important;
}
```
改完我觉得效果还行，只有当屏幕宽度小于 iPhone 5 (320px) 时才会显示滚动条
* https://www.responsinator.com/?url=https%3A%2F%2Fonedrive.moelab.top%2FVideos%2FAnime%2F%5BVCB-Studio%5D%2520White%2520Album%2520%5BHi10p_720p%5D%2FCDs%2F
* https://www.responsinator.com/?url=https%3A%2F%2Farchive.suisei.cc%2F3D%2520Live%2F

**Comment by aozaki-kuro** [comment]
已经按照 @0wQ 大佬提供的样式进行修改并部署，看起来非常不错！
个人来说这个问题已经解决了。

就是在close前还想问一下 @0wQ 大佬是如何实现给特定文件夹加密的呢？😂

**Comment by 0wQ** [comment]
> 已经按照 @0wQ 大佬提供的样式进行修改并部署，看起来非常不错！
> 个人来说这个问题已经解决了。
> 
> 就是在close前还想问一下 @0wQ 大佬是如何实现给特定文件夹加密的呢？😂

我已经提交 PR 啦 😂
#112

**Comment by tkfanswind** [comment]
>  min-width: 280px !important

大大这个修改是改的哪个文件改在哪个地方？

**Comment by sengoku-f** [comment]
> >  min-width: 280px !important
> 
> 
> 
> 大大这个修改是改的哪个文件改在哪个地方？

不改themes/spencer.css的话自己

**Comment by sengoku-f** [comment]
> >  min-width: 280px !important
> 
> 
> 
> 大大这个修改是改的哪个文件改在哪个地方？

在`htmlWrapper`添加自己的css链接就好啦

**Comment by tkfanswind** [comment]
> > > min-width: 280px !important
> > 
> > 
> > 大大这个修改是改的哪个文件改在哪个地方？
> 
> 在`htmlWrapper`添加自己的css链接就好啦

请问COMMIT_HASH怎么修改？ 这是什么东西。小白

**Comment by 0wQ** [comment]
> > min-width: 280px !important
> 
> 大大这个修改是改的哪个文件改在哪个地方？

直接写这里也行

https://github.com/spencerwooo/onedrive-cf-index/blob/21e1f4a0b5a24a1df49c1fb42941787a995cdb6c/src/render/htmlWrapper.js#L31-L50

```
<head>
  ...
  <style>
    div.path, a.item {
      word-break: break-all;
    }
    span.size {
      white-space: nowrap;
    }
    div.items > div {
      min-width: 280px !important;
    }
  </style>
</head>
```

**Comment by tkfanswind** [comment]
> > > min-width: 280px !important
> > 
> > 
> > 大大这个修改是改的哪个文件改在哪个地方？
> 
> 直接写这里也行
> 
> https://github.com/spencerwooo/onedrive-cf-index/blob/21e1f4a0b5a24a1df49c1fb42941787a995cdb6c/src/render/htmlWrapper.js#L31-L50
> 
> ```
> <head>
>   ...
>   <style>
>     div.path, a.item {
>       word-break: break-all;
>     }
>     span.size {
>       white-space: nowrap;
>     }
>     div.items > div {
>       min-width: 280px !important;
>     }
>   </style>
> </head>
> ```

修改COMMIT_HASH如何修改？

**Comment by sengoku-f** [comment]
> > > > min-width: 280px !important
> 
> > > 
> 
> > > 
> 
> > > 大大这个修改是改的哪个文件改在哪个地方？
> 
> > 
> 
> > 直接写这里也行
> 
> > 
> 
> > https://github.com/spencerwooo/onedrive-cf-index/blob/21e1f4a0b5a24a1df49c1fb42941787a995cdb6c/src/render/htmlWrapper.js#L31-L50
> 
> > 
> 
> > ```
> 
> > <head>
> 
> >   ...
> 
> >   <style>
> 
> >     div.path, a.item {
> 
> >       word-break: break-all;
> 
> >     }
> 
> >     span.size {
> 
> >       white-space: nowrap;
> 
> >     }
> 
> >     div.items > div {
> 
> >       min-width: 280px !important;
> 
> >     }
> 
> >   </style>
> 
> > </head>
> 
> > ```
> 
> 
> 
> 修改COMMIT_HASH如何修改？

htmlWrapper不用修改COMMIT_HASH

**Comment by tkfanswind** [comment]
const COMMIT_HASH = '85aa0b0' 
后面这个修改的值是怎么得来的？

**Comment by sengoku-f** [comment]
> const COMMIT_HASH = '85aa0b0' 
> 
> 后面这个修改的值是怎么得来的？

[自定义css](https://github.com/spencerwooo/onedrive-cf-index/issues/75#issuecomment-753567949)

**Comment by tkfanswind** [comment]
修改后效果图有吗？
