### ISSUE TITLE
publish后CF显示  Error 1101

### ISSUE THREAD

**Issue by imleft** [spencerwooo/onedrive-cf-index#90]
![2D0RDOGXU QP8VAU){N0MB8](https://user-images.githubusercontent.com/18010619/105213565-d3621600-5b89-11eb-9509-3e43134a9f00.png)
![LRLLD`3FUWR) E2GX_ (M`T](https://user-images.githubusercontent.com/18010619/105213718-03a9b480-5b8a-11eb-9d70-b11a5e6f15a7.png)
KV 存储（当前）
0 B/1 GB

**Comment by coxmos** [comment]
出现一样的问题..

**Comment by spencerwooo** [comment]
抱歉，报错信息给的严重不足，我看到你的 CloudFlare Worker 的 console 里面出现了 getAccessToken 失败以及 `9002313` 错误代码的报错信息，所以可能是 Azure Blade app 设置的权限不对？

**Comment by imleft** [comment]
解决,是refresh_token过期,用rclone重新获取了token

**Comment by WULANREN8177** [comment]
> 提示OAuth2授权码已被兑换为

出现了同样的问题，请问具体怎么解决的？
