### ISSUE TITLE
如何修改页面的图标， 就是favicon

### ISSUE THREAD

**Issue by huanx9** [spencerwooo/onedrive-cf-index#92]
readme里面没有写。 我也暂时没找到。。

**Comment by huanx9** [comment]
根据文件类型渲染文件图标，图标使用 Font Awesome icons；

**Comment by spencerwooo** [comment]
页面的 favicon，和文件图标，是两个不同的概念，希望你能具体说一下到底想要自定义哪个东西。页面 favicon 是整个网站的图标（也就是我们打开网页标签页上面的那个图标），由于 CloudFlare Worker 的限制，所以 favicon 只能用 base64 编码后通过 JavaScript 写入 HTML 渲染的部分，也就是 https://github.com/spencerwooo/onedrive-cf-index/blob/master/src/render/favicon.js 里面。如果你想要更改的是这个图标的话那么就需要改这部分。

**Comment by huanx9** [comment]
感谢解答。 已解决。
