### ISSUE TITLE
错误

### ISSUE THREAD

**Issue by xiaoxin2007** [spencerwooo/onedrive-cf-index#95]
{"error":"invalid_request","error_description":"AADSTS90023: Cross-origin token redemption is permitted only for the 'Single-Page Application' client-type.\r\nTrace ID: b02254c3-30be-44a1-86fc-a070aeb17b00\r\nCorrelation ID: 4374083d-538a-4ade-b051-94a2708758ec\r\nTimestamp: 2021-02-05 09:09:51Z","error_codes":[90023],"timestamp":"2021-02-05 09:09:51Z","trace_id":"b02254c3-30be-44a1-86fc-a070aeb17b00","correlation_id":"4374083d-538a-4ade-b051-94a2708758ec"}
这是我返回的代码，我的E5账户没问题，但是个人账户就这样了。我看过#13，但没看懂。

**Comment by spencerwooo** [comment]
https://github.com/spencerwooo/onedrive-cf-index/issues/13#issuecomment-671027672

**Comment by spencerwooo** [comment]
重点在于 "Step 5 - Exchange Access Token" 一步的请求需要手动构造，具体构造方法也就是链接 issue 提到的问题，请求建议使用 Insomnia 或者 Postman 发出，这样就能够成功获取 Access token 以及后续内容了。

**Comment by xiaoxin2007** [comment]
> 重点在于“第5步-Exchange访问令牌”一步的请求需要手动构造，具体构造方法也就是链接问题提到的问题，请求建议使用Insomnia或Postman发出，这样就能够成功获取Access令牌以及后续内容了。

谢谢！成功了！
另外，你有没有想过把获取网站绑定域名，这样就国内不用fq工具上了
